'use strict';
// THE SHARED CLI-CONFIG APPLIER (docs/design-harness-settings.zh.md §6,
// 2026-09-20). fs/path/os ONLY: this file's TEXT is embedded verbatim into the
// shipped remote helper (data/bin/vibespace-hook-register.mjs, generated by
// src/server/agent-tool-generators.js through createRequire) and required by
// the server for the local machine — ONE implementation of "write these
// managed keys (and our hook entries) into a harness's own config file" for
// every machine; the only difference is how the plan reaches it (in-process,
// ssh env, dial run-cmd env). It must never require anything from ORCH, never
// use __dirname/__filename (the helper is ESM), and every exported function
// must survive being evaluated inside a function body.
//
// TWO WRITERS, ONE LAW: read → mutate → compare-and-swap re-read right before
// the atomic tmp+rename (the lost-update window against a concurrent CLI write
// shrinks to the rename gap; the mutate is idempotent so a re-apply on fresher
// content is safe); a hand-broken file (invalid JSON, a TOML shape the setter
// does not understand) is REFUSED BY NAME and never overwritten; a missing
// file is created only when the plan says so and NEVER its directory (a
// missing ~/.codex means codex is not installed here).
//
// THE BYTES LAND ON THE REAL FILE (2026-09-21, verifier finding): a symlinked
// config — the dotfiles pattern, ~/.codex/config.toml → dotfiles/codex.toml —
// is written THROUGH: the tmp file goes beside the link's TARGET and the
// rename lands on the target, so the link survives and the dotfile keeps
// governing (a tmp+rename on the link path replaced it with a regular file,
// silently, at every boot/install/spawn); a dangling link is refused by name,
// never replaced; the file's own mode survives the rename (a 0600 config with
// tokens in it stays 0600 — the umask no longer decides). Every `rel` of a
// plan is re-checked HERE with the same rule as harness-settings.checkRel
// (this file cannot require it: the helper embeds this text alone): a `..`, a
// separator or a `~` segment is refused by name and never joined under $HOME,
// and decodePlan drops such a plan. The JSON writer re-serialises the WHOLE
// file (2-space JSON + trailing newline, exactly as Claude Code itself
// rewrites settings.json) — "only the touched line" is the TOML writer's
// promise, not this one's.
const fs = require('fs');
const path = require('path');
const os = require('os');

const HOOK_MARKER = 'vibespace-hook.mjs';

/** The descriptor-side file object for a table's `files.<id>` entry: the
 *  SAME `rel` array (test-harness-contract pins the identity — one spelling),
 *  plus the resolver and the create policy the writers need. */
function cliConfigFile(spec, { createIfMissing = false, writable = true, home = null } = {}) {
  if (!spec || !Array.isArray(spec.rel)) throw new Error('cliConfigFile: spec.rel required');
  return {
    rel: spec.rel, format: spec.format, createIfMissing: !!createIfMissing, writable: writable !== false,
    file: () => path.join(home || os.homedir(), ...spec.rel),
  };
}

// ── The write law shared by both writers ─────────────────────────────────────
/** The SAME four-line rule as harness-settings.checkRel (a twin by necessity —
 *  the shipped helper carries this file's text alone; test-harness-settings
 *  §6b pins the two spellings equal). null = sound, else the reason. */
function checkRel(rel) {
  if (!Array.isArray(rel) || !rel.length) return 'rel must be a non-empty array of path segments';
  for (const seg of rel) {
    if (typeof seg !== 'string' || !seg) return 'rel has an empty segment';
    if (seg === '..' || seg === '.') return `rel segment ${JSON.stringify(seg)} is not allowed`;
    if (seg.includes('/') || seg.includes('\\') || seg.startsWith('~')) return `rel segment ${JSON.stringify(seg)} must be a bare name (no separators, no ~)`;
  }
  return null;
}
/** The file's text, or null when it does not exist. A symlink whose target is
 *  gone is NOT "missing" — it is refused by name (a regular file created over
 *  it would silently break the dotfiles pattern); so is a file that exists
 *  but cannot be read (it would otherwise be "created" over). */
function readManaged(file) {
  try { return fs.readFileSync(file, 'utf-8'); } catch { }
  let st = null;
  try { st = fs.lstatSync(file); } catch { return null; }
  if (st.isSymbolicLink()) throw new Error(`${file} is a symlink whose target does not exist — not touching it`);
  throw new Error(`${file} exists but could not be read — not touching it`);
}
/** Where the bytes land and with which mode: a link's REAL target (the tmp
 *  file goes beside it, the rename lands on it) or the file itself; a missing
 *  file keeps its path and takes the umask's mode. */
function writeTarget(file) {
  let st = null;
  try { st = fs.lstatSync(file); } catch { return { target: file, mode: null }; }
  const target = st.isSymbolicLink() ? fs.realpathSync(file) : file;
  return { target, mode: fs.statSync(target).mode & 0o777 };
}
/** tmp beside the target → the file's own mode → atomic rename onto the target. */
function commitWrite(file, out) {
  const { target, mode } = writeTarget(file);
  const tmp = target + '.tmp';
  fs.writeFileSync(tmp, out, mode == null ? undefined : { mode });
  if (mode != null) fs.chmodSync(tmp, mode); // the umask clears bits at create time; the file's own mode wins
  fs.renameSync(tmp, target);
}

// ── JSON ─────────────────────────────────────────────────────────────────────
function getJsonPath(root, p) {
  let cur = root;
  for (const k of p) { if (!cur || typeof cur !== 'object') return undefined; cur = cur[k]; }
  return cur;
}
function setJsonPath(root, p, value) {
  let cur = root;
  for (let i = 0; i < p.length - 1; i++) {
    if (!cur[p[i]] || typeof cur[p[i]] !== 'object' || Array.isArray(cur[p[i]])) cur[p[i]] = {};
    cur = cur[p[i]];
  }
  cur[p[p.length - 1]] = value;
}
/** Read → mutate(root) → CAS → atomic write. `mutate` returns true when it
 *  changed something. Returns true when written, false when nothing changed.
 *  Throws (by name) on invalid JSON, a missing file without createIfMissing,
 *  a missing parent directory, or a file that keeps changing underneath. */
function writeJsonManaged(file, { createIfMissing = false } = {}, mutate) {
  const parse = () => ({ text: readManaged(file) });
  for (let attempt = 0; attempt < 4; attempt++) {
    const { text } = parse();
    let root = null;
    if (text != null) { try { root = JSON.parse(text); } catch { throw new Error(`${file} exists but is not valid JSON — not touching it`); } }
    if (!root || typeof root !== 'object' || Array.isArray(root)) {
      if (text != null) throw new Error(`${file} exists but is not valid JSON — not touching it`);
      if (!createIfMissing) throw new Error(`${file} not found (start the CLI once to create it)`);
      if (!fs.existsSync(path.dirname(file))) throw new Error(`${path.dirname(file)} not found (install the CLI first)`);
      root = {};
    }
    const changed = mutate(root);
    if (!changed) return false;
    const out = JSON.stringify(root, null, 2) + '\n';
    const cur = parse();
    if (cur.text !== text) continue; // someone wrote it — re-read + re-apply
    commitWrite(file, out);
    return true;
  }
  throw new Error(`${file} kept changing under concurrent writes — gave up`);
}
/** Our own hook entry in an event's group list (matched by the marker), or null. Never throws on a hand-edited shape. */
function findOurHookIn(list) {
  for (const group of Array.isArray(list) ? list : []) {
    if (!group || !Array.isArray(group.hooks)) continue;
    const h = group.hooks.find((x) => x && typeof x.command === 'string' && x.command.includes(HOOK_MARKER));
    if (h) return h;
  }
  return null;
}
/** Idempotent, NON-DESTRUCTIVE: add/update ONLY our entry under each event. Returns changed. */
function registerHookEntries(root, events, hookCmd) {
  if (!root.hooks || typeof root.hooks !== 'object' || Array.isArray(root.hooks)) root.hooks = {};
  let changed = false;
  for (const ev of events || []) {
    if (!Array.isArray(root.hooks[ev])) root.hooks[ev] = [];
    const ours = findOurHookIn(root.hooks[ev]);
    if (ours) { if (ours.command !== hookCmd) { ours.command = hookCmd; changed = true; } }
    else { root.hooks[ev].push({ hooks: [{ type: 'command', command: hookCmd, timeout: 10 }] }); changed = true; }
  }
  return changed;
}
/** Strip ONLY our entries from every event (a managed key is never touched). Returns changed. */
function stripHookEntries(root, events = null) {
  if (!root.hooks || typeof root.hooks !== 'object' || Array.isArray(root.hooks)) return false;
  let changed = false;
  for (const ev of events || Object.keys(root.hooks)) {
    if (!Array.isArray(root.hooks[ev])) continue;
    for (const group of root.hooks[ev]) {
      if (!group || !Array.isArray(group.hooks)) continue;
      const before = group.hooks.length;
      group.hooks = group.hooks.filter((h) => !(h && typeof h.command === 'string' && h.command.includes(HOOK_MARKER)));
      if (group.hooks.length !== before) changed = true;
    }
    root.hooks[ev] = root.hooks[ev].filter((g) => g && Array.isArray(g.hooks) && g.hooks.length);
  }
  return changed;
}

// ── TOML: a MINIMAL, comment-and-format-PRESERVING setter ───────────────────
// It edits ONE `key = value` line (string / boolean / integer) under a
// `[section]` (or a top-level key), leaving every other byte alone, and
// REFUSES BY NAME everything it does not fully understand: a key that lives in
// an inline table, an array of tables, a multi-line string, a value that is an
// array/inline table/float/date, a duplicate key, or a file its conservative
// line tokenizer cannot classify. "Refuse" means the file is not written.
const TOML_BARE_RE = /^[A-Za-z0-9_-]+$/;
const isWs = (c) => c === ' ' || c === '\t' || c === '\r';

/** Split a dotted key expression (`a.b`, `"x.y".z`, `'q'`) into parts; null when malformed. */
function splitKey(s) {
  const parts = []; let i = 0, cur = '';
  while (i < s.length) {
    const c = s[i];
    if (c === '"' || c === "'") {
      const close = s.indexOf(c, i + 1); if (close < 0) return null;
      cur += s.slice(i + 1, close); i = close + 1; continue;
    }
    if (c === '.') { if (!cur.trim()) return null; parts.push(cur.trim()); cur = ''; i++; continue; }
    cur += c; i++;
  }
  if (!cur.trim()) return null;
  parts.push(cur.trim());
  return parts;
}
/** Where a value's text ends on this line (before the trailing comment), and what shape it is. */
function scanValue(line, start) {
  let i = start;
  while (i < line.length && isWs(line[i])) i++;
  if (i >= line.length || line[i] === '#') return { kind: 'empty', start: i, end: i };
  const c = line[i];
  if (line.startsWith('"""', i) || line.startsWith("'''", i)) {
    const delim = line.slice(i, i + 3);
    const close = line.indexOf(delim, i + 3);
    if (close < 0) return { kind: 'multiline-open', delim, start: i, end: line.length };
    return { kind: 'multiline', start: i, end: close + 3 };
  }
  if (c === '"') {
    let j = i + 1;
    while (j < line.length) { if (line[j] === '\\') { j += 2; continue; } if (line[j] === '"') break; j++; }
    if (j >= line.length) return { kind: 'bad', start: i, end: line.length };
    return { kind: 'string', start: i, end: j + 1, raw: line.slice(i, j + 1) };
  }
  if (c === "'") {
    const j = line.indexOf("'", i + 1);
    if (j < 0) return { kind: 'bad', start: i, end: line.length };
    return { kind: 'string', start: i, end: j + 1, raw: line.slice(i, j + 1) };
  }
  if (c === '{') return { kind: 'inline-table', start: i, end: line.length };
  if (c === '[') {
    // arrays may span lines; find the matching close on THIS line (strings inside skipped)
    let depth = 0, j = i, inStr = null;
    for (; j < line.length; j++) {
      const ch = line[j];
      if (inStr) { if (ch === '\\' && inStr === '"') { j++; continue; } if (ch === inStr) inStr = null; continue; }
      if (ch === '"' || ch === "'") { inStr = ch; continue; }
      if (ch === '#') break;
      if (ch === '[') depth++; else if (ch === ']') { depth--; if (depth === 0) return { kind: 'array', start: i, end: j + 1 }; }
    }
    return { kind: 'array-open', start: i, end: line.length, depth };
  }
  let j = i;
  while (j < line.length && !isWs(line[j]) && line[j] !== '#') j++;
  const raw = line.slice(i, j);
  if (raw === 'true' || raw === 'false') return { kind: 'boolean', start: i, end: j, raw };
  if (/^[+-]?(?:0|[1-9](?:_?[0-9])*)$/.test(raw)) return { kind: 'integer', start: i, end: j, raw };
  if (/^0(?:x[0-9A-Fa-f_]+|o[0-7_]+|b[01_]+)$/.test(raw)) return { kind: 'integer', start: i, end: j, raw, radix: true };
  return { kind: 'other', start: i, end: j, raw };
}
/** Only whitespace or a `#` comment may follow a value/header on its line. */
function restIsTrivial(line, from) {
  let i = from;
  while (i < line.length && isWs(line[i])) i++;
  return i >= line.length || line[i] === '#';
}
/** THE CONSERVATIVE TOKENIZER. Every line becomes one of blank | table | aot |
 *  kv | opaque (inside a multi-line string or a multi-line array); anything
 *  else = {error}. Tables and array-of-table regions are tracked so a kv line
 *  knows which section it belongs to. */
function tomlTokenize(text) {
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const lines = text.split('\n');
  const toks = [];
  let section = null, sectionKind = 'root', multi = null, arrayDepth = 0;
  for (let n = 0; n < lines.length; n++) {
    const line = lines[n];
    if (multi) {
      const close = line.indexOf(multi);
      if (close >= 0) { if (!restIsTrivial(line, close + 3)) return { error: `line ${n + 1}: content after a multi-line string closes` }; multi = null; }
      toks.push({ kind: 'opaque', n, section, sectionKind });
      continue;
    }
    if (arrayDepth > 0) {
      let inStr = null;
      for (let j = 0; j < line.length; j++) {
        const ch = line[j];
        if (inStr) { if (ch === '\\' && inStr === '"') { j++; continue; } if (ch === inStr) inStr = null; continue; }
        if (ch === '"' || ch === "'") { inStr = ch; continue; }
        if (ch === '#') break;
        if (ch === '[') arrayDepth++; else if (ch === ']') { arrayDepth--; if (arrayDepth === 0) { if (!restIsTrivial(line, j + 1)) return { error: `line ${n + 1}: content after a multi-line array closes` }; break; } }
      }
      toks.push({ kind: 'opaque', n, section, sectionKind });
      continue;
    }
    let i = 0;
    while (i < line.length && isWs(line[i])) i++;
    if (i >= line.length || line[i] === '#') { toks.push({ kind: 'blank', n, section, sectionKind }); continue; }
    if (line[i] === '[') {
      const aot = line.startsWith('[[', i);
      const open = aot ? i + 2 : i + 1;
      const closeStr = aot ? ']]' : ']';
      const close = line.indexOf(closeStr, open);
      if (close < 0 || !restIsTrivial(line, close + closeStr.length)) return { error: `line ${n + 1}: malformed table header` };
      const parts = splitKey(line.slice(open, close));
      if (!parts) return { error: `line ${n + 1}: malformed table name` };
      section = parts.join('.'); sectionKind = aot ? 'aot' : 'table';
      toks.push({ kind: aot ? 'aot' : 'table', n, name: section, section, sectionKind });
      continue;
    }
    const eq = (() => { // first `=` outside quotes
      let inStr = null;
      for (let j = i; j < line.length; j++) {
        const ch = line[j];
        if (inStr) { if (ch === inStr) inStr = null; continue; }
        if (ch === '"' || ch === "'") { inStr = ch; continue; }
        if (ch === '=') return j;
      }
      return -1;
    })();
    if (eq < 0) return { error: `line ${n + 1}: not a key/value, table header or comment` };
    const keyParts = splitKey(line.slice(i, eq).trim());
    if (!keyParts) return { error: `line ${n + 1}: malformed key` };
    const v = scanValue(line, eq + 1);
    if (v.kind === 'bad' || v.kind === 'empty') return { error: `line ${n + 1}: unreadable value` };
    if (v.kind === 'multiline-open') multi = v.delim;
    else if (v.kind === 'array-open') arrayDepth = v.depth;
    else if (!restIsTrivial(line, v.end)) return { error: `line ${n + 1}: content after the value` };
    toks.push({ kind: 'kv', n, keyParts, section, sectionKind, value: v, eq });
  }
  return { eol, lines, toks };
}
function unquoteToml(raw) {
  if (raw[0] === "'") return raw.slice(1, -1);
  if (raw[0] === '"') {
    return raw.slice(1, -1).replace(/\\(u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8}|.)/g, (m, e) => {
      if (e[0] === 'u' || e[0] === 'U') return String.fromCodePoint(parseInt(e.slice(1), 16));
      return { n: '\n', t: '\t', r: '\r', b: '\b', f: '\f', '"': '"', '\\': '\\' }[e] ?? m;
    });
  }
  return raw;
}
function parseTomlScalar(v) {
  if (v.kind === 'string') return { kind: 'string', value: unquoteToml(v.raw) };
  if (v.kind === 'boolean') return { kind: 'boolean', value: v.raw === 'true' };
  if (v.kind === 'integer') { const n = Number(v.raw.replace(/_/g, '')); return Number.isSafeInteger(n) ? { kind: 'integer', value: n } : { kind: 'other' }; }
  return { kind: v.kind };
}
/** The one TOML value spelling this writer produces. */
function formatTomlValue(value) {
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') { if (!Number.isSafeInteger(value)) throw new Error(`toml: only integer numbers are supported (got ${value})`); return String(value); }
  if (typeof value === 'string') {
    const esc = { '\\': '\\\\', '"': '\\"', '\n': '\\n', '\t': '\\t', '\r': '\\r', '\b': '\\b', '\f': '\\f' };
    return '"' + value.replace(/[\\"\u0000-\u001f\u007f]/g, (c) => esc[c] || '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0')) + '"';
  }
  throw new Error(`toml: unsupported value type ${typeof value}`);
}
/** Locate the kv token that holds `section.key` (section null = top level).
 *  Returns {tok} | {refused} | {} (absent). */
function tomlLocate(tk, section, key) {
  const want = section ? [section, key] : [key];
  let hit = null, header = -1, dotted = -1;
  for (const t of tk.toks) {
    if (section && t.kind === 'table' && t.name === section) header = t.n;
    if (t.kind !== 'kv') continue;
    // `section.other = …` at the top level DEFINES the table by dotted keys
    if (section && t.sectionKind === 'root' && t.keyParts.length >= 2 && t.keyParts[0] === section) dotted = t.n;
    const full = t.sectionKind === 'root' ? t.keyParts : [...t.section.split('.'), ...t.keyParts];
    if (full.length !== want.length || full.some((p, i) => p !== want[i])) {
      // `section = { key = … }` (inline table at root) or `section = 5` (a
      // root scalar of that name): a `[section]` table cannot coexist with
      // either — codex 0.154.0 refuses the file as "duplicate key"
      if (section && t.sectionKind === 'root' && t.keyParts.length === 1 && t.keyParts[0] === section) {
        if (t.value.kind === 'inline-table') return { refused: `${section} is an inline table on line ${t.n + 1}` };
        return { refused: `${section} is already a value on line ${t.n + 1} — a [${section}] table cannot coexist with it` };
      }
      continue;
    }
    if (t.sectionKind === 'aot') return { refused: `${want.join('.')} lives in an array of tables ([[${t.section}]], line ${t.n + 1})` };
    if (hit) return { refused: `${want.join('.')} appears twice (lines ${hit.n + 1} and ${t.n + 1})` };
    hit = t;
  }
  if (section) for (const t of tk.toks) if (t.kind === 'table' && t.name === `${section}.${key}`) return { refused: `${section}.${key} is a table ([${t.name}], line ${t.n + 1})` };
  // dotted keys AND a header for the same table = a duplicate definition (TOML
  // forbids both orders; codex 0.154.0: "duplicate key") — already broken by
  // hand, never made "applied" by us
  if (section && header >= 0 && dotted >= 0) return { refused: `${section} is defined both by dotted keys at the top level (line ${dotted + 1}) and as a [${section}] table (line ${header + 1})` };
  if (hit) {
    const k = hit.value.kind;
    if (k === 'multiline' || k === 'multiline-open') return { refused: `${want.join('.')} is a multi-line string (line ${hit.n + 1})` };
    if (k === 'inline-table') return { refused: `${want.join('.')} is an inline table (line ${hit.n + 1})` };
    if (k === 'array' || k === 'array-open') return { refused: `${want.join('.')} is an array (line ${hit.n + 1})` };
    if (k === 'other') return { refused: `${want.join('.')} has a value this writer does not handle (line ${hit.n + 1})` };
    return { tok: hit };
  }
  return {};
}
/** Read one scalar: {found:false} | {found:true, kind, value} | {refused}. */
function tomlGet(text, section, key) {
  const tk = tomlTokenize(text);
  if (tk.error) return { refused: tk.error };
  const loc = tomlLocate(tk, section, key);
  if (loc.refused) return { refused: loc.refused };
  if (!loc.tok) return { found: false };
  return { found: true, ...parseTomlScalar(loc.tok.value) };
}
/** Set/replace `section.key = value`. Returns {text, changed} or {refused}.
 *  Existing section → the new line goes after the section's last key line;
 *  the file already spelling it `section.key = …` at top level → that line is
 *  replaced in place; missing section → appended at the end. Byte-identical
 *  output when the value is already there (idempotent). */
function tomlSet(text, section, key, value) {
  if (section != null && !TOML_BARE_RE.test(section)) return { refused: `section ${JSON.stringify(section)} is not a bare name` };
  if (!TOML_BARE_RE.test(key)) return { refused: `key ${JSON.stringify(key)} is not a bare name` };
  let spelled;
  try { spelled = formatTomlValue(value); } catch (e) { return { refused: e.message }; }
  const tk = tomlTokenize(text);
  if (tk.error) return { refused: `could not read the file conservatively (${tk.error})` };
  const loc = tomlLocate(tk, section, key);
  if (loc.refused) return { refused: loc.refused };
  const { lines, eol } = tk;
  if (loc.tok) {
    const cur = parseTomlScalar(loc.tok.value);
    if (cur.kind !== 'other' && cur.value === value && typeof cur.value === typeof value) return { text, changed: false };
    const line = lines[loc.tok.n];
    lines[loc.tok.n] = line.slice(0, loc.tok.value.start) + spelled + line.slice(loc.tok.value.end);
    return { text: lines.join('\n'), changed: true };
  }
  const newLine = `${key} = ${spelled}`;
  const cr = eol === '\r\n' ? '\r' : '';
  const lastLine = lines[lines.length - 1];
  const endsWithNewline = lastLine === '' || lastLine === '\r';
  const insertAfter = (n, extra) => {
    const out = [...lines];
    out.splice(n + 1, 0, ...extra.map((s) => s + cr));
    return out.join('\n');
  };
  if (section) {
    let header = -1, lastKv = -1, lastDotted = -1;
    for (const t of tk.toks) {
      // `section.other = …` at the top level already DEFINES the table: a
      // `[section]` header appended later is a duplicate definition (codex
      // 0.154.0 refuses the file), so the new line keeps the file's spelling
      if (t.kind === 'kv' && t.sectionKind === 'root' && t.keyParts.length >= 2 && t.keyParts[0] === section) lastDotted = t.n;
      if (header >= 0 && (t.kind === 'table' || t.kind === 'aot') && t.n > header) break;
      if (t.kind === 'table' && t.name === section) { header = t.n; lastKv = t.n; continue; }
      if (header >= 0 && t.section === section && t.sectionKind === 'table' && (t.kind === 'kv' || t.kind === 'opaque')) lastKv = t.n;
    }
    if (header >= 0) return { text: insertAfter(lastKv, [newLine]), changed: true };
    if (lastDotted >= 0) return { text: insertAfter(lastDotted, [`${section}.${key} = ${spelled}`]), changed: true };
    // missing section → append at the end (blank-line separated)
    const body = text.length === 0 ? '' : (endsWithNewline ? text : text + eol);
    const sep = body.length === 0 || body.endsWith(eol + eol) ? '' : eol;
    return { text: body + sep + `[${section}]` + eol + newLine + eol, changed: true };
  }
  // top-level key: after the last root kv, else before the first table header
  let lastRoot = -1, firstHeader = -1;
  for (const t of tk.toks) {
    if (t.kind === 'table' || t.kind === 'aot') { firstHeader = t.n; break; }
    if (t.kind === 'kv' || t.kind === 'opaque') lastRoot = t.n;
  }
  if (lastRoot >= 0) return { text: insertAfter(lastRoot, [newLine]), changed: true };
  if (firstHeader >= 0) return { text: insertAfter(firstHeader - 1, [newLine, '']), changed: true };
  const body = text.length === 0 ? '' : (endsWithNewline ? text : text + eol);
  return { text: body + newLine + eol, changed: true };
}
/** Read → apply every set → CAS → atomic write. `sets` = [{path:[section,key]|[key], value}].
 *  Any refusal throws BY NAME and nothing is written. Returns true when written. */
function writeTomlManaged(file, { createIfMissing = false } = {}, sets) {
  const read = () => readManaged(file);
  for (let attempt = 0; attempt < 4; attempt++) {
    const text = read();
    let cur = text;
    if (cur == null) {
      if (!createIfMissing) throw new Error(`${file} not found (start the CLI once to create it)`);
      if (!fs.existsSync(path.dirname(file))) throw new Error(`${path.dirname(file)} not found (install the CLI first)`);
      cur = '';
    }
    let changed = false;
    for (const s of sets) {
      const section = s.path.length === 2 ? s.path[0] : null;
      const key = s.path[s.path.length - 1];
      const r = tomlSet(cur, section, key, s.value);
      if (r.refused) throw new Error(`${file}: ${r.refused} — not touching it`);
      if (r.changed) { cur = r.text; changed = true; }
    }
    if (!changed) return false;
    if (read() !== text) continue;
    commitWrite(file, cur);
    return true;
  }
  throw new Error(`${file} kept changing under concurrent writes — gave up`);
}

// ── THE PLAN: apply / read / receipts ────────────────────────────────────────
const RECEIPT_STATES = Object.freeze(['applied', 'unchanged', 'differs', 'missing', 'unreadable', 'refused', 'error', 'unknown']);
const relOf = (f) => (Array.isArray(f.rel) ? f.rel.join('/') : String(f.rel || ''));
const receipt = (f, s, state, extra = {}) => ({ harness: f.harness, id: f.id, rel: relOf(f), key: s ? s.key : null, path: s ? s.path.join('.') : null, want: s ? s.value : undefined, state, ...extra });
/** Apply `plan` under `home`: managed keys always; our hook entries when
 *  `hookCmd` is given (the remote helper) — `uninstall` strips ONLY the hook
 *  entries and never a managed key. Returns per-key receipts + per-file hook
 *  outcomes. Never throws for one file's failure: it is reported by name. */
function applyConfigPlan(plan, { home = null, hookCmd = null, uninstall = false } = {}) {
  const base = home || os.homedir();
  const receipts = [], files = [];
  for (const f of (plan && Array.isArray(plan.files)) ? plan.files : []) {
    const sets = uninstall ? [] : (Array.isArray(f.set) ? f.set : []);
    const hooks = f.hooks && Array.isArray(f.hooks.events) && f.format === 'json' && hookCmd ? f.hooks.events : null;
    const touchesHooks = !!hooks || (uninstall && f.format === 'json' && !!f.hooks);
    if (!sets.length && !touchesHooks) continue;
    const badRel = checkRel(f.rel); // the plan is trusted nowhere: a `..` here would leave $HOME
    if (badRel) {
      for (const s of sets) receipts.push(receipt(f, s, 'refused', { reason: badRel }));
      files.push({ harness: f.harness, id: f.id, rel: relOf(f), file: null, hooks: touchesHooks ? 'error' : null, error: badRel });
      continue;
    }
    const file = path.join(base, ...f.rel);
    const out = { harness: f.harness, id: f.id, rel: relOf(f), file, hooks: touchesHooks ? 'unchanged' : null };
    try {
      if (f.format === 'json') {
        const before = {};
        const written = writeJsonManaged(file, { createIfMissing: !!f.createIfMissing && !uninstall }, (root) => {
          let changed = false;
          if (uninstall) { if (stripHookEntries(root)) { changed = true; out.hooks = 'stripped'; } }
          else if (hooks) { if (registerHookEntries(root, hooks, hookCmd)) { changed = true; out.hooks = 'registered'; } }
          for (const s of sets) {
            const cur = getJsonPath(root, s.path);
            before[s.key] = cur;
            if (cur !== s.value) { setJsonPath(root, s.path, s.value); changed = true; }
          }
          return changed;
        });
        for (const s of sets) receipts.push(receipt(f, s, before[s.key] === s.value ? 'unchanged' : 'applied', { current: s.value, previous: before[s.key] === undefined ? null : before[s.key] }));
        out.written = !!written;
      } else if (f.format === 'toml') {
        const written = writeTomlManaged(file, { createIfMissing: !!f.createIfMissing }, sets);
        for (const s of sets) receipts.push(receipt(f, s, written ? 'applied' : 'unchanged', { current: s.value }));
        out.written = !!written;
      } else {
        throw new Error(`unknown config format ${JSON.stringify(f.format)}`);
      }
    } catch (e) {
      const state = /not found/.test(e.message) ? 'missing' : /not valid JSON|not touching it|could not read/.test(e.message) ? 'refused' : 'error';
      for (const s of sets) receipts.push(receipt(f, s, state, { reason: e.message }));
      out.error = e.message; if (touchesHooks) out.hooks = 'error';
    }
    files.push(out);
  }
  return { receipts, files };
}
/** READ-ONLY: what each managed key is on disk right now (never writes). */
function readConfigPlan(plan, { home = null } = {}) {
  const base = home || os.homedir();
  const receipts = [];
  for (const f of (plan && Array.isArray(plan.files)) ? plan.files : []) {
    const sets = Array.isArray(f.set) ? f.set : [];
    if (!sets.length) continue;
    const badRel = checkRel(f.rel);
    if (badRel) { for (const s of sets) receipts.push(receipt(f, s, 'refused', { reason: badRel })); continue; }
    const file = path.join(base, ...f.rel);
    let text = null;
    try { text = fs.readFileSync(file, 'utf-8'); } catch { }
    if (text == null) { for (const s of sets) receipts.push(receipt(f, s, 'missing')); continue; }
    if (f.format === 'json') {
      let root = null;
      try { root = JSON.parse(text); } catch { }
      if (!root || typeof root !== 'object') { for (const s of sets) receipts.push(receipt(f, s, 'unreadable', { reason: 'not valid JSON' })); continue; }
      for (const s of sets) { const cur = getJsonPath(root, s.path); receipts.push(receipt(f, s, cur === s.value ? 'applied' : 'differs', { current: cur === undefined ? null : cur })); }
    } else if (f.format === 'toml') {
      for (const s of sets) {
        const section = s.path.length === 2 ? s.path[0] : null;
        const g = tomlGet(text, section, s.path[s.path.length - 1]);
        if (g.refused) receipts.push(receipt(f, s, 'unreadable', { reason: g.refused }));
        else if (!g.found) receipts.push(receipt(f, s, 'differs', { current: null }));
        else receipts.push(receipt(f, s, g.kind !== 'other' && g.value === s.value ? 'applied' : 'differs', { current: g.kind === 'other' ? '(unsupported value)' : g.value }));
      }
    } else for (const s of sets) receipts.push(receipt(f, s, 'unreadable', { reason: `unknown format ${f.format}` }));
  }
  return receipts;
}
// Receipt lines on the remote helper's stdout — one per managed key:
//   CFG|<harness>|<key>|<state>|<current>|<want>|<reason>
// the three free-text fields are encodeURIComponent(JSON) so neither a `|` nor
// a newline in a value can shear the line.
const enc = (v) => encodeURIComponent(JSON.stringify(v === undefined ? null : v));
const dec = (s) => { try { return JSON.parse(decodeURIComponent(s)); } catch { return null; } };
function formatReceiptLines(receipts) {
  return (receipts || []).map((r) => ['CFG', r.harness, r.key, r.state, enc(r.current), enc(r.want), enc(r.reason || null)].join('|')).join('\n');
}
function parseReceiptLines(text) {
  const out = [];
  for (const line of String(text || '').split('\n')) {
    const p = line.trim().split('|');
    if (p[0] !== 'CFG' || p.length < 4) continue;
    if (p[1] === '*') { out.push({ harness: null, key: null, state: 'unknown', reason: p[3] === 'unknown' ? 'helper predates --status' : p[3] }); continue; }
    out.push({ harness: p[1], key: p[2], state: RECEIPT_STATES.includes(p[3]) ? p[3] : 'unknown', current: dec(p[4] || ''), want: dec(p[5] || ''), reason: dec(p[6] || '') });
  }
  return out;
}
/** The design's name for "apply this plan here" (test-claude-retention §1 keeps it): applyConfigPlan with named options. */
function ensureCliConfig({ plan, home = null, hookCmd = null, uninstall = false } = {}) { return applyConfigPlan(plan, { home, hookCmd, uninstall }); }
/** The plan on the wire: base64 JSON (shell-safe: [A-Za-z0-9+/=] only). */
function encodePlan(plan) { return Buffer.from(JSON.stringify(plan), 'utf8').toString('base64'); }
function decodePlan(b64) {
  if (!b64 || typeof b64 !== 'string') return null;
  try {
    const p = JSON.parse(Buffer.from(b64, 'base64').toString('utf8'));
    // a plan with an unsound rel is dropped whole (the helper then applies its hooks-only DEFAULT_PLAN)
    return p && p.v === 1 && Array.isArray(p.files) && p.files.every((f) => f && typeof f === 'object' && !checkRel(f.rel)) ? p : null;
  } catch { return null; }
}

module.exports = {
  HOOK_MARKER, RECEIPT_STATES, cliConfigFile, checkRel,
  getJsonPath, setJsonPath, writeJsonManaged, findOurHookIn, registerHookEntries, stripHookEntries,
  tomlTokenize, tomlGet, tomlSet, formatTomlValue, writeTomlManaged,
  applyConfigPlan, readConfigPlan, ensureCliConfig, formatReceiptLines, parseReceiptLines, encodePlan, decodePlan,
};
