'use strict';
// SESSION FIELD SCHEMA (拆分P3 — the blackboard gets owners).
// The live session object in activeSessions accumulated ~50 underscore fields
// written from anywhere ("blackboard" anti-pattern): nothing said which module
// owned a field, what persisted it, or whether two writers raced. This module
// is the AUTHORITATIVE registry — every `session._field` write site must have
// a row here. scripts/test-session-schema.mjs enforces it: an unregistered
// write FAILS the suite until the field is added WITH an owner; a dead row
// must be removed. PURE module (no requires) — safe to import anywhere.
//
// owner values name the module that conceptually owns writes:
//   stdout    src/server/session-stdout.js (the parse + meta store)
//   ws        src/ws-handler.js / src/ws-create.js (protocol handlers)
//   goal      src/server/goal-sync.js + the set-goal ws case
//   pool      src/server/usage-pool-engine.js (model lock / pool identity)
//   brain     src/server/session-brain.js (dual-feed gate)
//   boot      src/server/boot-restore.js (restore-time backfill)
//   dial      dial/agentd transport plumbing
//   channel-touches  src/server/channel-touches.js (the channel witness, §26)
//   group-cards      src/normalizers.js feedGroupCard (the group-card door) + src/server/channels-wiring.js (its meta write)
//   bridge    src/server/bridge-watch.js (the dead-bridge watch: heal budget, catch-up, lane-dead-bridge)
// persisted: 'meta' = session-meta json, 'wrapper' = wrapper meta file,
//            null = in-memory only (dies with the process by design).
// config:    { key, example } = the field's value RIDES A RESUME through the client's
//            per-session config (user-state `sessionConfigs[key]`, written by
//            sidebar.setSessionConfig, read back by session-lifecycle's resume as
//            `savedCfg.<key>`). THE RESUME CARRIER CENSUS (test-session-schema, verify r2
//            of lane-pool-pin): setSessionConfig keeps only what it names, and that list
//            silently dropped 'account' (2.43.0), 'groupManager' (2.132.0), 'outputStyle' +
//            'autoResume' (2.368.0) and 'poolPin' (2026-09-28) — so every key declared
//            here is DRIVEN through the real setSessionConfig with its `example` and must
//            come back whole, and every key the resume reads / a writer writes must be
//            declared here (or in SESSION_CONFIG_ONLY below). A row whose `persisted`
//            says 'session-config' must carry `config`.

const SESSION_FIELDS = {
  // identity / lifecycle
  _webuiId:            { owner: 'brain',  persisted: null,      note: 'webui id stamped for device-feed side effects' },
  _opencodePtyId:      { owner: 'ws',     persisted: null,      note: 'S9 remainder (c): the OpenCode serve pty this terminal session bridges (pty_… on the serve, not a local process)' },
  _normalizer:         { owner: 'stdout', persisted: null,      note: 'MessageManager instance for the live stream' },
  _normEpoch:          { owner: 'stdout', persisted: null,      note: 'normalizer identity epoch — client full-reset discriminator (2.89.x)' },
  _opRing:             { owner: 'stdout', persisted: null,      note: "the session's OP RING (src/op-seq.js, perf lane chunk D): the last ≤ 2000 / ≤ 4 MiB `msg` frames the broadcast choke point (src/server/session-broadcast.js) stamped with `seq`, kept as the exact text sent — a same-epoch re-attach with `sinceSeq` inside it gets them replayed (`attached {slab:'held', replay}`) instead of a slab. Created on the first stamped frame, reset with `_normEpoch` by rebuildHistory; in-memory by nature (a restart is a new epoch)" },
  _subNormalizers:     { owner: 'stdout', persisted: null,      note: 'per-subagent normalizers map' },
  _taskRecordsTimer:   { owner: 'stdout', persisted: null,      note: 'debounce for the taskRecords session-meta write' },
  _artifactsTimer:     { owner: 'stdout', persisted: null,      note: 'debounce for the artifacts session-meta write (src/server/artifact-registry.js)' },
  _helperAskedAt:      { owner: 'stdout', persisted: 'session-meta helperAskedAt', note: 'lane S1 verify r3: {requestId: ms} — each WAITING helper ask\'s first-seen instant, written by helper-asks.sync when the map changes, restored by boot-restore, stamped onto the rebuilt ask by rebuildHistory so the 60 s For-you clock does not restart with the server' },
  _helperAskedAtKey:   { owner: 'stdout', persisted: null,      note: 'lane S1 verify r3: the JSON of the last persisted _helperAskedAt map (write only on change)' },
  _channelTouches:     { owner: 'channel-touches', persisted: 'session-meta channelTouches', note: 'the channel WITNESS ring (§26, B-099e): every agent read / search / reply / compose / refresh / request / status of a channel conversation this session made, recorded by the agent routes through src/server/channel-touches.js (newest 200, a repeat inside 2 s folded); restored by all three boot-restore paths so the chat rows survive a restart' },
  _groupCards:         { owner: 'group-cards', persisted: 'session-meta groupCards', note: 'lane group-report-card: THE GROUP-CARD RING (src/group-card.js) — one entry per group message this conversation was handed, keyed (group id, record instant): a next-turn report\'s card (placed BY TIME by rebuildHistory, so it survives a restart) or a wake\'s card with `recordedHead` (the transcript holds that post — the rebuild upgrades that record into the group card, never a second one); written by the card door src/normalizers.js feedGroupCard, persisted by channels-wiring on a microtask (before the report\'s marker write), restored by all three boot-restore paths; bounded (RING_MAX)' },
  _artifacts:          { owner: 'stdout', persisted: 'session-meta artifacts', note: 'the conversation\'s deliverable rows (src/artifacts.js) — written by the stdout consumers through src/server/artifact-registry.js (observe / touch), re-derived from the transcript and merged on every rebuild (lane artifacts-model)' },
  _taskRecords:        { owner: 'stdout', persisted: 'session-meta taskRecords', note: 'latest task_started / task_progress (tree kept field-wise) / task_notification per tool_use_id — replayed into the normalizer after a rebuild (2.369.140: the records are live-only and the stdout ring drops them)' },
  _historyLoaded:      { owner: 'ws',     persisted: null,      note: 'first-attach full-JSONL rebuild flag (set AFTER success, 2.89.2)' },
  _heldPeerCards:      { owner: 'ws',     persisted: null,      note: 'verify r5 (S2): the display-only peer cards (no msgId) fed by normalizers.feedPeerCard BEFORE the first-attach rebuild — bounded (32), replayed by rebuildHistory after the history and cleared; a card fed during the rebuild rides _rebuildQueue instead. In memory: a restart loses them like every injected card (the zero-spend notice is the durable half).' },
  _rebuildQueue:       { owner: 'ws',     persisted: null,      note: 'live records held back during the time-sliced first-attach rebuild, replayed in order (2.369.16 feedLive gate)' },
  _rebuildPromise:     { owner: 'ws',     persisted: null,      note: 'single-flight rebuild promise — concurrent attaches await it instead of rebuilding twice (2.369.16)' },
  _rebuildProgress:    { owner: 'ws',     persisted: null,      note: '{done,total} of the in-flight rebuild — rides the 10s progress attach-acks (2.369.16)' },
  _jobsEventsSeenTs:   { owner: 'agent-routes', persisted: null, note: 'Background Work event delivery marker (2.342.0) — restart = full redelivery, mirroring group-snap semantics' },
  _csiAccepted:        { owner: 'jobs-wiring', persisted: null,  note: 'crossSessionInbound=accept pushed to this pre-2.344.0 live chat session via apply_flag_settings (2.344.1 catch-up; restart = harmless re-push)' },
  _startSubagentWatcher: { owner: 'stdout', persisted: null,    note: 'bound helper for restart re-arm of agent watchers' },
  _retireCompaction:   { owner: 'stdout', persisted: null,      note: "bound `retireCompaction(session, id)` from the claude stdout consumer (§2.11, round 7): the TEARDOWN path is a turn-lifecycle exit this consumer never sees a record for, and it must retire the 'compacting' claim through the SAME named function (broadcast + clear) instead of reaching in and clearing _streamingKind silently" },
  _settleTurnLane:     { owner: 'stdout', persisted: null,      note: "bound `settleTurnLane(session)` from the claude stdout consumer (2026-09-13 r3) — the SAME teardown debt as _retireCompaction, for the per-turn LANE decision. An unscoped weekly rejection defers its BUCKET MARK to the end of the turn, and `settleTurnLane` is reachable only from `noteTurnEnd` (claude's `result` record); a turn that ends by the WRAPPER DYING produces none, so the wall was dropped entirely where master's immediate write left a mark — and a dropped wall makes the member read healthy to every other conversation" },

  // streaming / turn state
  _isStreaming:        { owner: 'stdout', persisted: 'wrapper', note: 'explicit protocol-signal streaming flag (never heuristic)' },
  _streamingLabel:     { owner: 'stdout', persisted: null,      note: 'current activity label (thinking/tool/responding)' },
  _autoResume:         { owner: 'ws',     persisted: 'session-config', config: { key: 'autoResume', example: false }, note: 'per-session auto-continue-after-limit preference (undefined = follow claude.autoResumeOnLimit; 2.368.0)' },
  _outputStyle:        { owner: 'ws',     persisted: 'session-meta',   config: { key: 'outputStyle', example: 'Explanatory' }, note: 'the EFFECTIVE response style this session runs with (claude output style / codex Personality). Spawn-scoped on claude (--settings, stream-json has no /output-style); LIVE on codex (thread/settings/update) — capsOf(backend).responseStyle.live decides. 2.368.0, generalized 2.369.58; persisted so a server restart does not report "default" for a session really running one' },
  _streamingKind:      { owner: 'ws',     persisted: null,      note: 'streaming-label kind (compacting) — drives the client Stop two-step guard; set on a /compact send, reset with the label at turn end (2.365.0); also set/cleared by the compact_progress records (§2.11)' },
  _turnState:          { owner: 'stdout', persisted: null,      note: "the harness's OWN turn state, last observed: 'idle'|'running'|'requires_action' (claude system/session_state_changed, env-gated at spawn — §2.5). Drives _isStreaming authoritatively and gives the status bar its third state; in-memory because it is a statement about a RUNNING process (a restart re-derives from the sidecar until the next record)" },
  _turnStateSeen:      { owner: 'stdout', persisted: null,      note: 'THIS session has produced at least one authoritative turn-state record — the latch that stands the derived result/user inference down. False forever on an old CLI / a spawn without the env: degradation is the default path (§3.5)' },
  _inProgressTools:    { owner: 'stdout', persisted: null,      note: "Set<tool_use_id> currently executing, from claude's set_in_progress_tool_use_ids {op:{action,ids}} (caps.inProgressTools). Live-only by nature — the tool cards' spinner set, pushed as 'tools-in-progress' and carried on the attach payload" },
  _codexResetTriedAt:  { owner: 'engine', persisted: null,      note: 'reset-credit attempt stamp (2.368.21) — the one-try floor itself is PER IDENTITY since 2.369.157 r2 (the engine\'s `_resetCreditTries`, read by the verdict\'s `cooldownUntilSec` and the manual preview); this stamp remains the attempt time the result handler falls back to' },
  _resetCreditEvent:   { owner: 'engine', persisted: null,      note: 'the limit EVENT the reset-credit rung last spoke about (`<identity>|<stated reset>`, design-reset-credits §3): the wall card (and the journal line) fire once per event however many records restate the wall; the ask item keys on `_resetCreditAsked` (r2)' },
  _resetCreditOrigin:  { owner: 'engine', persisted: null,      note: 'whose reset-credit attempt the next `reset_credit_result` answers — \'auto\' (the rung) or \'user\' (the manual button, design-reset-credits p2): a failed USER attempt is reported and never walked down the switch/wait ladder; cleared by the result' },
  _resetCreditKey:     { owner: 'engine', persisted: null,      note: 'the credit IDENTITY this session\'s last reset-credit attempt was written for (design-reset-credits r2): the key of the engine\'s per-identity attempt record whose followers the `reset_credit_result` settles, and whose cache the "superseded" check reads' },
  _resetCreditStale:   { owner: 'engine', persisted: null,      note: 'this process\'s codex wrapper had a consume REFUSED for the missing idempotencyKey (it predates the key fix — codex refused it locally, nothing sent; lane reset-path): the auto rung skips it by name (no retry loop on a refusal that cannot change until Terminate + Resume), and a person\'s press goes to the helper process (the preview carries only wrappers advertising `resetCreditKey`)' },
  _resetCreditAsked:   { owner: 'engine', persisted: null,      note: 'the limit event (`<identity>|<stated reset>`) the ask-mode For-you decision was filed for — ONE item per event whether it was asked at the wall or, for a cold conversation, after a switch that moved nothing (r2)' },
  _heldPoolMember:     { owner: 'ws',     persisted: 'session-meta heldPoolMember', note: 'the pool member a process on a backend that cannot hot-switch (capsOf(backend).hotSwitch !== verified — codex canonicalizes CODEX_HOME at startup) HOLDS for its whole life, stamped at spawn after resolveForSpawn\'s self-heal; heldPoolMemberFor/sessionBillingMember resolve the session\'s billing member to it so a credit, a reading, a wall and a fire after a pool re-point name the login the process really speaks as (design-reset-credits r2). null = a hot pool / no pool / spawned before the stamp' },
  _poolPin:            { owner: 'pool',   persisted: 'session-meta poolPin', config: { key: 'poolPin', example: { memberId: 'sub-0a1b2c3d4e5f', at: 1790000000000, poolId: 'pool-0a1b2c3d4e5f' } }, note: "THE CONVERSATION'S POOL PIN (2026-09-28, owner: \"如果选择某个具体账号，那在这个账号耗尽之前就pin在这个账号下，刷新后也优先切到这个账号\"): {memberId, at, by:'user'} or null. Written by ONE writer (usage-pool-engine setConversationPin, behind POST /api/accounts/:poolId/pin); read by the per-session pass (decidePinnedPlacement BEFORE decidePoolSwitch — pin > pool priority order > automatic), the spawn chooser (a resume starts on the pinned member when it can serve) and sessionAuth (the chip / Session Properties / the billing submenu). Persisted into session-meta (a server restart restores it at all three boot-restore sites); a RESUME carries it through the client's session config (`poolPin`, the conversation's own choice); a FORK starts unpinned (ws-create ignores it on a fork)" },
  _heldPoolOrigin:     { owner: 'engine', persisted: 'session-meta heldPoolOrigin', note: 'where `_heldPoolMember` came from (design-reset-credits r3/r4): \'ledger\' = the process was spawned before the stamp existed and the slot-transition ledger named the pool default at its createdAt (accounts.poolMemberOfSession — the last default row before it, else the `from` of the first one after it: STABLE across later moves) — memoized onto the session AND persisted into its meta with the stamp, so a restart restores the answer instead of re-deriving it; \'no-start\' = restored from a meta with no createdAt (boot-restore: the ledger cannot place it ⇒ unknown — r5: the marker itself is PERSISTED into the meta as heldPoolOrigin by the first restore, because the rename / thread-meta writers then persist the boot-filled createdAt); \'unknown\' = only the journal\'s say-once marker (an unknown answer is NOT memoized — one unreadable ledger read must not pin a process unknown for life)' },
  _heldRestartAskedAt: { owner: 'engine', persisted: null,      note: 'when a client was last asked to cold-restart this conversation (`pool-auto-switched`): stamped by the ONE sender (usage-pool-engine sendColdRestart — the default switch, the per-session switch, the auth-failure evict, requestHeldRestart) and by claimColdRestarts (the manual pool target / member-narrowing routes, whose response the client acts on); every one of them leaves out a conversation asked inside 10 min (a second request resumes the conversation twice), and the reset-credit preview names a carrier in that state (`restartPending`)' },
  _resetCreditsSeen:   { owner: 'engine', persisted: null,      note: 'the stored reset-credit count this session\'s own wrapper last reported ({count, at, key} — it rides ONLY the on-demand account/rateLimits/read): the rung\'s fallback when a later passive push dropped it from the account cache, and only for the identity `key` it was read for (p2: a pool session switched to another member never offers the old member\'s count)' },
  _turnWallSigs:       { owner: 'engine', persisted: null,      note: 'wall machine (2.369.0): wall signals accumulated on the CURRENT turn ({at, resetsAtMs, bucket, scopedName, key, slot} — key = the cache key the mark landed on (a REJECTION keys to the credential SLOT since 2026-09-07, a reading keys org-verified), slot = whether that key WAS the validated slot when the rejection arrived); the FIRST keyed signal PINS both for the rest of the turn (rejectionSlotFor — the first record of a rejection re-points the link by itself); the result record classifies' },
  _turnReadingSlot:    { owner: 'engine', persisted: null,      note: 'readings-by-slot (2026-09-07): the validated credential slot ({key, slotOk, at}) this turn\'s quota READINGS are attributed to, resolved ONCE per turn by readingSlotFor and cleared by noteTurnEnd — the twin of _turnWallSigs\' rejection pin. Without it a turn\'s ~20 readings split across the members our own mid-turn re-points moved to, crediting numbers to an account that served none of that turn' },
  _turnLaneDefer:      { owner: 'engine', persisted: null,      note: "the LANE of this turn's UNSCOPED weekly rejections is not decided yet (2026-09-13): [{key, resetsAt, rawType, at}]. claude 2.1.267 has no `seven_day_<model>` type, so a MODEL-cap rejection arrives on the plain `seven_day` lane and only the banner text names the model — writing the event immediately marked the PLAN week 100% spent for three members at once. The bucket mark waits for the banner (kind 'scoped' ⇒ that model's cap, carrying the event's own resetsAt) or, with no banner, for the turn-end evidence rule; the SIGNAL is raised at once so the session is still walled and the pool still moves. Cleared by noteTurnEnd with the other three turn pins" },
  _turnBannerLane:     { owner: 'engine', persisted: null,      note: "the LANE this turn's limit banner named ({kind: a model cap ('scoped' + name) or the plan week, at}; B-ccaa 2026-09-16): laneFromBanner fires when the banner arrives, but a banner that arrived BEFORE the rejection found nothing pending — so a deferral that arrives after it, and the turn-end settle, consult this memo before the evidence rule. A 5-hour banner names no weekly lane and is not kept. Cleared by noteTurnEnd with the other turn pins" },
  _recordClock:        { owner: 'engine', persisted: null,      note: "the STREAM CLOCK of the late-record rule (lane-hot-switch, src/record-lateness.js): {stampAt, arrivedAt, delayMs} of the last record the CLI STAMPED (claude 2.1.281 stamps every `assistant` record at emission). An unstamped record (`rate_limit_event`, `result`) that arrives within BURST_MS inherits its verdict. Written by noteStreamRecord, fed by BOTH feeds first" },
  _lateBurst:          { owner: 'engine', persisted: null,      note: 'the current BACKLOG episode ({n, maxLateMs, kinds, at}): late facts counted once and journalled at its start and its end (the first live stamped record closes it) — never one line per record' },
  _heldLate:           { owner: 'engine', persisted: null,      note: "lane reset-path verify r7 ④: the late facts gated while the stream has NO declared clock offset, each with its own replay — [{what, lateMs, at, replay}], newest HELD_LATE_MAX (32); replayed through their gates at the declaration (replayHeldLate), discarded when a live record ends the burst (endLateBurst: it was a backlog)" },
  _peekStamp:          { owner: 'stdout', persisted: null,      note: "the claude parse's LOOK-AHEAD for the late-record rule: `() => nextStampIn(lineBuf)` — the stamp of the next stamped record already in this attach's buffer, asked only for an unstamped live fact with no stamped neighbour behind it (a rejected turn's `rate_limit_event` precedes its stamped error record by ms)" },
  _turnWallRefuted:    { owner: 'engine', persisted: null,      note: "the wall attribution REFUTED the turn pin for this turn ({from, reason, at} — wallRecordTarget archived a rejection record whose stated reset contradicts the pin's own window, lane-hot-switch 2026-09-30). The window-less banner of the same wall and the turn-end fold ask it (wallAttributionFor), so the pin is never marked, demoted, excluded from this conversation or counted in the ≥2-walls ring for a wall it did not answer. Cleared by noteTurnEnd with the re-file proof" },
  _turnWallRefile:     { owner: 'engine', persisted: null,      note: 'the wall attribution PROVED, for this turn, that a rejection record belongs to another member ({from, to, at} — wallRecordTarget re-filed it on the slot ledger plus the window). One wall reaches us through up to three producers and only the rate_limit_event carries a window: the two banner paths state no time at all (parseLimitBanner returns {kind}), so without this they fall back to the turn pin — the member just proved innocent — and one rejection marks two members. Cleared by noteTurnEnd with the other two turn pins' },
  _lastReadingFp:      { owner: 'engine', persisted: null,      note: 'lag shadow (inc-mts8a8mr-ulmm): {key, fp} — the last window fingerprint we filed under a given slot. The SERVER twin of the statusline tool\'s `.slot-<id>` sidecar, and the only evidence left when two members share a weekly reset phase or neither window is established yet ("the link moved but the numbers did not ⇒ leave them where they were")' },
  _readingShadowEndedAt: { owner: 'engine', persisted: null,    note: 'lag shadow: the `at` of the re-point whose shadow has already ended for this session. The FIRST reading that is demonstrably the new credentials\' ends the shadow, and it stays ended — a later in-flight straggler is not evidence that the new credentials have not answered' },
  _turnWorkAfterSig:   { owner: 'engine', persisted: null,      note: 'wall machine: assistant records seen after the last wall signal (work evidence → turn classifies NORMAL)' },
  _wallProbeTimer:     { owner: 'engine', persisted: null,      note: 'wall machine: pending quota-probe backoff timer (30m→1h→2h) when no reset time is known' },
  _arFiring:           { owner: 'auto-resume', persisted: null, note: 'async pre-fire gate in flight (probe+verdict) — tick skips the session meanwhile' },
  _codexLastResetsAt:  { owner: 'engine', persisted: null,      note: 'resets_at (unix sec) of the codex limit that triggered the reset-credit try — auto-resume arms from it if the credit fails (2.368.21)' },
  _codexLastLane:      { owner: 'engine', persisted: null,      note: 'limitId of the codex window that triggered the reset-credit try — the arm carries it so the fresh-window edge cannot be fooled by a sibling lane (2026-09-08)' },
  _codexLimitsWaiters: { owner: 'engine', persisted: null,      note: 'rpc-rate-limits probe waiters (S4 caps-routed quota probe): {resolve,timer} entries settled by the next rate_limits_updated AFTER its cache write; bounded by a timeout' },
  _interruptTimer:     { owner: 'ws',     persisted: null,      note: 'delayed-SIGINT fallback handle (2s, cancel on protocol success)' },
  _exitAsked:          { owner: 'ws',     persisted: null,      note: 'B-f698: {by, at} — VibeSpace asked this CLI to exit (by=interrupt: the Stop\'s SIGINT fallback; terminate: the kill case; user-signal / user-kill: the System panel / kill-pid doors). Fresh 30 s; the exit line says asked=<by> and an asked exit is never "unexpected" (src/exit-facts.js)' },
  _wrapperFrameFile:   { owner: 'ws',     persisted: null,      note: 'wrapper understands _frame_file pointers (meta.caps at wrapper boot, chat-wrapper AND codex-chat-wrapper; 2.361.1 skew gate — old wrappers silently DROP pointer lines; positive verdict only)' },
  _userInputAt:        { owner: 'ws',     persisted: null,      note: "the last instant a PERSON sent this session input (ws 'input' keystrokes / 'chat-input'). With _machineInputAt it tells prompt-context whether the turn it is asked about is the owner's own — next-turn group reports ride ONLY those (design-communication-panel §22 D2). In memory: a restart with neither stamp reads as a user turn" },
  _machineInputAt:     { owner: 'deliver', persisted: null,     note: 'the last instant a turn NOBODY TYPED was handed to this session — the delivery ladder at every local rung (conversation-deliver machineTurn) auto-resume\'s continue (server.js sendToSession) and a dispatch\'s `/compact` (user-input.js origin \'dispatch\', lane worker-dispatch). Newer than _userInputAt ⇒ the prompt-context call is a machine turn and the group reports wait (§22 D2)' },
  _draftEditAt:        { owner: 'ws',     persisted: null,      note: "the last instant a PERSON edited this session's chat draft (ws 'state-set' on the drafts store, key chat:<id>, non-empty) — a person COMPOSING a reply has not sent yet, so _userInputAt is stale, but they are using the conversation. The user-active fence (lane worker-dispatch dispatch-model targetFacts) reads max(_userInputAt, _draftEditAt): a dispatch never compacts a worker whose owner is mid-draft. In memory only (a draft's own text persists in drafts.json; this instant does not)" },
  _msgReachability:    { owner: 'agent',  persisted: 'meta',    note: 'per-session external reach override for agent messaging (2.362.0 Channels v1: inherit|visible|messageable, widening only; set via Session Properties)' },
  _stdinAckReceived:   { owner: 'stdout', persisted: null,      note: 'wrapper _stdin_ack seen — broken-pty detector input' },
  _lastPtyDataAt:      { owner: 'stdout', persisted: null,      note: 'THE liveness stamp: the instant ANY byte last arrived from this session\'s pty bridge (stamped in setupSessionPty, the one place every pty is wired). Read by `ptyQuietSince` for BOTH liveness triggers — the attach probe (no dtach redraw preamble within 4.6s of attach ⇒ the device channel never opened) and ws-handler\'s broken-stdin detector (which used to read session.buffer.length, a strict subset: the terminal branch swallows the preamble and a chat consumer need not append every byte)' },
  _ptyOpenedAt:        { owner: 'stdout', persisted: null,      note: 'lane-dead-bridge verify r1: the instant the CURRENT pty bridge was wired (setupSessionPty) — with _lastPtyDataAt it answers "has THIS bridge spoken since it was opened": a dtach client that spoke its attach preamble connected to a live master, which holds every input it forwarded in its socket queue and reads it even after the client dies, so the broken-stdin detector must NOT re-send through the new attach (it delivered the message twice — reproduced); only a bridge that never spoke has nothing queued' },
  _bridgeHeldInputs:   { owner: 'stdout', persisted: null,      note: 'B-c20d: the inputs typed into a bridge that has NOT spoken yet ({pty, lines, replaying}) — the ONE healer replays them in order through the new attach (writeSessionInput holds, takeHeldInputs/replayHeldInputs in src/server/session-stdout.js); ends at the bridge\'s first byte; `pty: null` = carried by the onExit ladder to its re-attach (verify r1: a never-spoke pty that exits forwarded nothing)' },
  _attachProbeHeals:   { owner: 'stdout', persisted: null,      note: 'how many CONSECUTIVE times the attach liveness probe re-attached THIS session locally — bounded at 2 so a systemically silent bridge cannot become a heal loop; reset to 0 by any attach that produces a byte (a lifetime cap would spend a long-lived session\'s heals on unrelated hiccups and leave the next one dark)' },
  _bridgeHeals:        { owner: 'bridge', persisted: null,      note: "lane-dead-bridge: the instants the dead-bridge watch (src/server/bridge-watch.js) re-attached THIS session in the last hour — the heal budget (3 / hour, PURE healBudget), so a bridge that stays dead cannot become a heal loop" },
  _bridgeCatchUp:      { owner: 'bridge', persisted: null,      note: "lane-dead-bridge: the CATCH-UP a heal (or the boot orphan sweep) released — {st, why, note(msg)}; the claude stdout consumer calls note() for every record while it drains (counted through record-lateness's rule), and ONE card says what was lost and when; cleared when the backlog drains (a live-stamped record or 15 s quiet)" },
  _bridgeEmptyHeals:   { owner: 'bridge', persisted: null,      note: "lane-dead-bridge: consecutive heals that brought NOTHING (no record, nothing past dtach's 6-byte preamble) — each doubles this session's silence threshold (a CLI whose API requests print nothing is quiet, not dead); any heal that brings output resets it" },
  _pendingEditor:      { owner: 'ws',     persisted: null,      note: 'Ctrl+G editor open in flight' },

  // goal
  _goal:               { owner: 'goal',   persisted: 'wrapper', note: 'active objective text' },
  _goalStatus:         { owner: 'goal',   persisted: 'wrapper', note: 'active/paused/blocked/usageLimited/…' },
  _goalElapsed:        { owner: 'goal',   persisted: 'wrapper', note: 'seconds used' },
  _goalTokensUsed:     { owner: 'goal',   persisted: 'wrapper', note: 'tokens used' },
  _prevGoal:           { owner: 'goal',   persisted: 'wrapper', note: 'replaced goal for /goal resume' },
  _lastGoalStatusUuid: { owner: 'goal',   persisted: null,      note: 'JSONL goal_status dedup cursor' },
  _goalJsonlFetchAt:   { owner: 'goal',   persisted: null,      note: 'remote transcript pull throttle for goal sync' },

  // model / billing identity
  _servedModel:        { owner: 'stdout', persisted: null,      note: 'last MAIN-THREAD assistant model (never sidechain). WRITTEN through the engine\'s granular consumer `noteServedModel` (like markLimitBanner/recordRateLimitEvent) so the parse and the device feed share ONE implementation of the fallback rule beside it' },
  _servedModelAt:      { owner: 'stdout', persisted: null,      note: 'timestamp of the above' },
  _servedViaFallback:  { owner: 'stdout', persisted: 'meta',      note: "THE CLI ANSWERED WITH A MODEL WE DID NOT ASK FOR (2026-09-13): {from,to,at} from a `fallback` content block / a `system/model_refusal_fallback` record on the MAIN thread. The safety classifier's reroute is announced ONCE and `scope:'session'` — the incident's next 18 assistant records carried claude-opus-4-8 with no marker at all — so the fact has to live on the SESSION, not be re-derived per record. `sessionModelFor` refuses to let a served model that IS this `to` define the session's model; cleared the moment a main-thread record is served by anything else. PERSISTED since 2026-09-13 r3: the round-1 argument (`boot-restore's ladder falls to picked/spawn = the REQUEST model`) is true of the LADDER and false of everything else — a restored conversation got ONE main-thread opus record, nothing on the session refuted it, `servedDefinesModel` said yes and the pool moved it onto a member whose Fable cap was 100 % spent (reproduced on the real engine). The reroute is announced ONCE, so it can never be re-learned from the stream; only the file carries it. Written by the two granular consumers (`noteModelFallback` / `noteServedModel`'s retirement branch), restored at all THREE boot-restore sites. A STALE ONE CANNOT SPEND MONEY — `projectionFamilyFor` answers null (every bucket counts) and the REQUEST model wins — but it is not free either (r3-r2, the round-3 verifier): with every bucket counting it can also refuse a move OFF a member that is hard-dead, because a candidate's cap OUTSIDE this session's family still counts against it (measured on the real engine: a 5h-100% current member kept the conversation while a free member sat beside it, blocked on an Opus cap the session was not using). That is the conservative direction, r2 strands identically — persisting it only makes the state survive a restart instead of being cleared by one — and it self-heals at the first main-thread record served by anything else" },
  _accountId:          { owner: 'ws',     persisted: 'session-meta accountId', config: { key: 'account', example: 'sub-0a1b2c3d4e5f' }, note: "the billing identity this session spawned under (an account or a pool id; set at spawn from the create's `accountId`, re-pointed by the billing switcher's restart). Written in ws-create's session literal (the write detector sees only `x._f =`), so this row exists for the RESUME CARRIER: the client's per-session config `account` is what a resume sends back as `accountId`" },
  _pickedModel:        { owner: 'pool',   persisted: 'meta',    note: 'set-model pick (plan C identity ladder)' },
  _pickedModelAt:      { owner: 'pool',   persisted: 'meta',    note: 'timestamp of the pick' },
  _nameExplicit:       { owner: 'ws',     persisted: 'meta',    note: 'lane peer-card-sender: the live name was GIVEN (ws create `sessionName`, a ws rename-session) — the sidebar card shows it before the first message; meta `nameExplicit`, restored by boot-restore' },
  _spawnModel:         { owner: 'ws',     persisted: 'meta',    config: { key: 'model', example: 'claude-fable-5-1' }, note: 'model at spawn (identity ladder fallback)' },
  _modelLocked:        { owner: 'pool',   persisted: 'meta',    config: { key: 'modelLock', example: true }, note: 'per-conversation model lock flag' },
  _lockedModel:        { owner: 'pool',   persisted: 'meta',    config: { key: 'lockModel', example: 'claude-fable-5-1' }, note: 'lock target (full id upgraded from the CLI echo)' },
  _fallbackStopFired:  { owner: 'pool',   persisted: null,      note: 'once-per-turn stop-on-fallback belt latch' },
  _apiKeySource:       { owner: 'stdout', persisted: 'meta',    note: "CLI's own init apiKeySource (billing truth)" },
  _effort:             { owner: 'ws',     persisted: 'meta',    config: { key: 'effort', example: 'high' }, note: 'effort the NEXT turn will run at; ws on a client pick, and (2.369.62) the codex stdout consumer from wrapper_meta.effortNext — a `/effort` typed into the chat used to leave this stale for the next resume' },
  _permissionMode:     { owner: 'ws',     persisted: 'meta',    config: { key: 'permission', example: 'plan' }, note: 'launch/set permission mode (not in JSONL)' },
  _modelOrigin:        { owner: 'ws',     persisted: 'meta',    note: "WHICH FACT the spawn's model came from (B-6b6d): 'chosen' (a pick for this session) | 'conversation' (its own last turn — codex turn_context / claude's last assistant record) | 'instance' (<prefix>.defaultModel) | 'harness' (nothing sent). Not derivable downstream: the conversation's own value and the instance default are frequently the same string" },
  _effortOrigin:       { owner: 'ws',     persisted: 'meta',    note: "the effort twin of _modelOrigin (B-6b6d). claude has NO conversation source for effort, so a claude resume with no pick is 'harness' — the instance default is a NEW-session default. RE-AUTHORED after the spawn: ws set-effort ⇒ 'chosen'; the codex stdout consumer ⇒ 'conversation' when the wrapper reports a value we never commanded (it adopted the thread's), 'chosen' when it moves away from one we did. EVERY re-author persists it with the value it describes (round 3: the stdout consumer wrote only `effort`, so boot-restore rebuilt the SPAWN's origin for a value the user had changed by hand)" },

  // resume / fork
  _forkRequested:      { owner: 'ws',     persisted: null,      note: 'one-shot fork flag gating id adoption (2.156.1); restored from meta `forkRequested` only while the record still names its source (claude-lock-capture restoredForkPending) — dtach AND R6 pipe restores' },
  _resumeSpawn:        { owner: 'ws',     persisted: 'meta',    note: 'spawn was a --resume (implicit-fork adoption gate)' },
  _sawFirstId:         { owner: 'stdout', persisted: 'meta',    note: 'first id line consumed (adoption bookkeeping)' },
  _resumeSwept:        { owner: 'ws',     persisted: null,      note: 'writer sweep SWEPT: pids for the created reply' },
  _resumeWarning:      { owner: 'ws',     persisted: null,      note: 'non-fatal resume degradation note for the client' },
  _reattachAttempts:   { owner: 'stdout', persisted: null,      note: 'bounded dead-socket re-attach counter' },
  _droppedLines:       { owner: 'stdout', persisted: null,      note: "per-kind counters of stream lines the claude chat consumer could not use (`cli-unparsable-line` / `cli-line-handler-error`) — exact counts; the log line AND the telemetry event are rate-limited by them (first 3, then every 100th — round 4) (fork-group round 3: a dropped record is never silent)" },
  _cwdRecreated:       { owner: 'ws',     persisted: 'meta',    note: 'B-7812 recreate-cwd notice armed' },
  _browserKey:         { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P0 (design-agent-browser-v2 §3.2.1): `bk-<8 hex>`, this CONVERSATION\'s browser identity. Minted once, recovered on resume from data/browser-env/bindings.json FIRST (written at session-stdout\'s one meta choke point and never unlinked by a kill — r5: the conversation→webui-key join is only the second rung, because the kill and pty-exit paths delete the meta file this row persists to, so the join alone never served a Terminate → Resume), re-minted on fork — and a fork\'s record states `forkSourceId` so the choke point never binds the PARENT conversation to the fork\'s key (r6: a claude/codex fork names the parent\'s id until the harness announces its own), while a resume\'s record states `browserKeyFor` = the conversation the key was DECIDED for, so an id the harness announces INSTEAD (an implicit fork adopted by the consumer) is never bound to it and mints its own key on its next resume (r7; the store also refuses to bind a new conversation to a key another one holds). It names the AGENT_BROWSER_SESSION/_NAMESPACE this session spawned with, so two sessions stop opening and closing each other\'s tabs; persisted because keying on the webui id (which changes every resume) leaks a browser, a daemon and a pinned tab per resume' },
  _browserVariant:     { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P0 (§3.2.2/D12): which user-data-dir rung this spawn landed on — D (generated config, truly ephemeral, carries the effective fence) / C (per-session scratch dir under data/, swept) / N (the three names alone, reachable ONLY when the effective config names no profile — then each daemon gets the CLI\'s own ephemeral dir; also where every FENCED session lands when D is unavailable, because rung C is an AGENT_BROWSER_PROFILE the CLI refuses beside --allowed-domains — r4) / none (nothing emitted, today\'s shared browser: the local floor when the config names a profile and neither D nor C is available — the names alone would put N browsers on ONE dir and the second fails to launch, measured) / H (REMOTE: decided on the host at spawn between C and N by that machine\'s own config, through the `browser` fragment of buildRemoteExec). The design\'s A and B are named rejects (browser-profiles.REJECTED_VARIANTS, both measured to collide). Recorded so a log line or a properties row states the rung instead of re-deriving it' },
  _browserProfileId:   { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P1 (design-agent-browser-v2 §3.2.5): the profile this session is PINNED to (`bp-<8 hex>`), or null = ephemeral. Decided at spawn by the keeper\'s ladder (explicit > this conversation\'s pin > Task-Group default > instance default > none) and rewritten by the pin route mid-session; the conversation-level fact lives in data/browser-profiles.json `pins` (keyed by browserKey), this is the session\'s copy for the properties row and the restart.' },
  _browserPinOrigin:   { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P1: WHICH rung chose `_browserProfileId` — one of browser-profiles.PIN_ORIGINS (chosen / conversation / task-group / instance / harness), stated by the ladder, never inferred (the B-6b6d rule).' },
  _browserEnv:         { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P2 (design §4.2): the P0 spawn pairs (`AGENT_BROWSER_*=…`) this process browses with, kept so the live view of an EPHEMERAL browser (no attachment) asks `stream status` under exactly these — never a re-run of the ladder, which would rebuild the generated config (the r3 finding). null = nothing emitted (rung none / integration off / remote).' },
  _browserCap:         { owner: 'ws',     persisted: 'meta',    note: 'MULTIVIEW D4 (docs/design-browser-multiview.zh.md): this conversation\'s EXPLICIT per-conversation browser cap (1..6), or null = follow the default (its Task Group\'s `browserCap` > setting browser.defaultPerConversationCap > 3). The conversation-level fact is the keeper\'s `caps` (keyed by browserKey, like `pins` — a resume keeps it); this is the session\'s copy, stamped at spawn from the keeper and rewritten by POST /api/browser/cap (the strip\'s own/cap chip, Session Properties), published as `browserCap` in active-sessions.' },
  _browserHelpers:     { owner: 'stdout', persisted: null,      note: 'MULTIVIEW §4 (B-89d0): the helper-naming WITNESS state (src/browser-stream.js bindHelpers — Task openings, sidechain `vibespace-browser new-child` Bash calls, the handles the keeper minted), fed by src/server/browser-helpers.js from the claude stdout consumer and the new-child route. A helper is named from its Task description only when, at the CLOSE of its witness (the Bash tool_result), exactly one mint arrived inside its window, no other witness was open in it and the result names that handle (lane P verify); never by time or order. In memory: after a restart every helper reads "Helper N".' },
  _browserProfileActive: { owner: 'ws',   persisted: 'meta',    note: 'agent-browser P2 (design §3.8 layer ③): the profile the agent LAST ACTUALLY USED — stamped by /api/agent/browser/resolve on every successful CLI command (an attachment\'s id, or \'\' for the ephemeral browser); null = the agent has not issued a browser command yet. Beside `_browserProfileId` (the PINNED default) it is the status-bar Browser chip\'s pair: amber when they differ. Published as `browserProfileActive` in active-sessions and gated by its own LIVE_SESSION_FACTS digest.' },
  _worktree:           { owner: 'ws',     persisted: 'meta',    config: { key: 'worktree', example: false }, note: 'the user asked THIS session to run in its own git worktree (claude --worktree, owner ruling 9). Persisted so a restart/resume keeps describing the session honestly and the badge survives; the FLAG itself is only re-emitted on a fork (worktreeSpawnArgs) because the CLI re-enters its recorded worktree on --resume by itself' },
  _worktreePath:       { owner: 'stdout', persisted: 'meta',    note: 'the worktree directory the CLI ITSELF announced in its init frame `cwd` (typed record, never inferred: the CLI chdir\'s into <repo>/.claude/worktrees/<name> and reports it). null until the first init frame; Session Properties shows it'  },

  // remote / transport
  _remoteState:        { owner: 'stdout', persisted: 'wrapper', note: 'remote keeper link state (reconnecting chip)' },
  _vcs:                { owner: 'brain',  persisted: 'meta',    note: "design-unknown-records (2026-09-21): the LAST claude `vcs_state_changed` fact {kind, branch, cwd, at} — session-brain noteVcsState writes it from either feed; rides active-sessions as `vcs` (the card's git chip) + the `session-vcs` push (explorer refresh); persisted so the chip survives a restart" },
  _prLinks:            { owner: 'brain',  persisted: 'meta',    note: "design-unknown-records (2026-09-21): the published changes this session announced (`code_change_published` → [{url, identifier, repo, action, provider, at}], ≤20, keyed by url) — session-brain notePublishedChange; rides active-sessions as `prLinks` (the card's PR chips); the url is UNVERIFIED by the CLI's own words — shown, never fetched" },
  _remotePort:         { owner: 'ws',     persisted: null,      note: 'reverse-tunnel port for VIBESPACE_API' },
  _agentdSession:      { owner: 'ws',     persisted: 'meta',    note: 'daemon pipe-session marker (R6/M2)' },
  _agentdCfgFile:      { owner: 'ws',     persisted: null,      note: 'attach-cli cfg file path (cleanup)' },
  _dialDeviceId:       { owner: 'dial',   persisted: 'meta',    note: 'owning dial device id' },
  _dialReversePort:    { owner: 'dial',   persisted: null,      note: 'device-side reverse forward port' },
  _bridgePort:         { owner: 'dial',   persisted: 'meta',    note: 'DialSessionBridge loopback port' },

  // agent-facing bookkeeping (src/agent-routes.js) — the injection ladder's
  // per-session "already delivered this" marks, plus the Stop nudge's clock.
  // Registered 2026-09-08: the detector only saw `session.`/`sess.` receivers,
  // and every one of these is written through a local named `s`/`sessionObj`.
  _lastStopNudge:      { owner: 'agent-routes', persisted: 'spend-budget', note: "the Stop bookkeeping nudge's cooldown (design-account-hardening D8). The in-memory mirror of the PERSISTED record in data/spend-budget.json (src/server/spend-guard.js `nudgeRec`/`noteNudge`): it was in-memory ONLY, so every release restart handed the largest measured automatic spender (603 mini-turns over two months here, 21 of them on one conversation inside one hour) a fresh cooldown. The route takes the NEWER of the two" },
  _preambleSeen:       { owner: 'agent-routes', persisted: null, note: 'hash of the task-context preamble already delivered to this session (re-delivery only when the content changes)' },
  _toolsIntroSeen:     { owner: 'agent-routes', persisted: null, note: 'the baseline tools intro has been delivered to this no-task session (SessionStart)' },
  _mgrIntroSeen:       { owner: 'agent-routes', persisted: null, note: 'the manager-agent intro has been delivered (shared latch between SessionStart and prompt-context — whichever delivers first wins)' },
  _groupSeenAt:        { owner: 'agent-routes', persisted: null, note: '{groupId: contentUpdatedAt} the session has already been shown — the per-turn group-diff cursor' },
  _ctxSig:             { owner: 'agent-routes', persisted: null, note: '{groupId: contextDirSignature} at last delivery — a ctx folder change re-injects' },
  _groupSnap:          { owner: 'agent-routes', persisted: null, note: '{groupId: snapshotForDiff} at last delivery — what the update diff is computed against' },

  // misc consumers
  _sizeOwnerWs:        { owner: 'ws',     persisted: null,      note: 'size-override owner connection' },
  _childPid:           { owner: 'boot',   persisted: 'meta',    note: 'the pid INSIDE the dtach session (the wrapper/CLI, not our pty) — restored from session-meta at boot and used by the kill path' },
  _restoreAgentTasks:  { owner: 'boot',   persisted: null,      note: "the wrapper meta's subagent task map, carried from restore until setupSessionPty's watcher is armed, then cleared (null = consumed)" },
  _todos:              { owner: 'stdout', persisted: null,      note: 'TodoWrite/TaskCreate-derived {done,total,current}' },
  _sbSeen:             { owner: 'brain',  persisted: null,      note: 'first-writer-wins record gate (bounded set)' },
  _codexThreadBaseline: { owner: 'ws',    persisted: null,      note: 'codex thread listing baseline for capture' },
  _captureReservedThreadId: { owner: 'ws', persisted: null,     note: 'codex reserved thread id during create' },
};

// Per-session config keys that are NOT a live-session field (the resume carrier census above):
// each names the module that reads it and why it has no session row. An entry whose reader no
// longer mentions it FAILS the census (the allowlist cannot go stale around a key).
const SESSION_CONFIG_ONLY = {
  groupManager: { reader: 'src/agent-routes.js', example: true, why: "the Session Properties 'group manager' toggle — read server-side straight from user-state sessionConfigs (agent-routes), never copied onto the live session" },
};

module.exports = { SESSION_FIELDS, SESSION_CONFIG_ONLY };
