'use strict';
// SESSION FIELD SCHEMA (拆分P3 — the blackboard gets owners).
// The live session object in activeSessions accumulated ~50 underscore fields
// written from anywhere ("blackboard" anti-pattern): nothing said which module
// owned a field, what persisted it, or whether two writers raced. This module
// is the AUTHORITATIVE registry — every `session._field` write site must have
// a row here. scripts/test-session-schema.mjs enforces it: an unregistered
// write FAILS the suite until the field is added WITH an owner; a dead row
// must be removed. PURE module (no requires) — safe to import anywhere.
//
// owner values name the module that conceptually owns writes:
//   stdout    src/server/session-stdout.js (the parse + meta store)
//   ws        src/ws-handler.js / src/ws-create.js (protocol handlers)
//   goal      src/server/goal-sync.js + the set-goal ws case
//   pool      src/server/usage-pool-engine.js (model lock / pool identity)
//   brain     src/server/session-brain.js (dual-feed gate)
//   boot      src/server/boot-restore.js (restore-time backfill)
//   dial      dial/agentd transport plumbing
// persisted: 'meta' = session-meta json, 'wrapper' = wrapper meta file,
//            null = in-memory only (dies with the process by design).

const SESSION_FIELDS = {
  // identity / lifecycle
  _webuiId:            { owner: 'brain',  persisted: null,      note: 'webui id stamped for device-feed side effects' },
  _opencodePtyId:      { owner: 'ws',     persisted: null,      note: 'S9 remainder (c): the OpenCode serve pty this terminal session bridges (pty_… on the serve, not a local process)' },
  _normalizer:         { owner: 'stdout', persisted: null,      note: 'MessageManager instance for the live stream' },
  _normEpoch:          { owner: 'stdout', persisted: null,      note: 'normalizer identity epoch — client full-reset discriminator (2.89.x)' },
  _subNormalizers:     { owner: 'stdout', persisted: null,      note: 'per-subagent normalizers map' },
  _taskRecordsTimer:   { owner: 'stdout', persisted: null,      note: 'debounce for the taskRecords session-meta write' },
  _taskRecords:        { owner: 'stdout', persisted: 'session-meta taskRecords', note: 'latest task_started / task_progress (tree kept field-wise) / task_notification per tool_use_id — replayed into the normalizer after a rebuild (2.369.140: the records are live-only and the stdout ring drops them)' },
  _historyLoaded:      { owner: 'ws',     persisted: null,      note: 'first-attach full-JSONL rebuild flag (set AFTER success, 2.89.2)' },
  _rebuildQueue:       { owner: 'ws',     persisted: null,      note: 'live records held back during the time-sliced first-attach rebuild, replayed in order (2.369.16 feedLive gate)' },
  _rebuildPromise:     { owner: 'ws',     persisted: null,      note: 'single-flight rebuild promise — concurrent attaches await it instead of rebuilding twice (2.369.16)' },
  _rebuildProgress:    { owner: 'ws',     persisted: null,      note: '{done,total} of the in-flight rebuild — rides the 10s progress attach-acks (2.369.16)' },
  _jobsEventsSeenTs:   { owner: 'agent-routes', persisted: null, note: 'Background Work event delivery marker (2.342.0) — restart = full redelivery, mirroring group-snap semantics' },
  _csiAccepted:        { owner: 'jobs-wiring', persisted: null,  note: 'crossSessionInbound=accept pushed to this pre-2.344.0 live chat session via apply_flag_settings (2.344.1 catch-up; restart = harmless re-push)' },
  _startSubagentWatcher: { owner: 'stdout', persisted: null,    note: 'bound helper for restart re-arm of agent watchers' },
  _retireCompaction:   { owner: 'stdout', persisted: null,      note: "bound `retireCompaction(session, id)` from the claude stdout consumer (§2.11, round 7): the TEARDOWN path is a turn-lifecycle exit this consumer never sees a record for, and it must retire the 'compacting' claim through the SAME named function (broadcast + clear) instead of reaching in and clearing _streamingKind silently" },
  _settleTurnLane:     { owner: 'stdout', persisted: null,      note: "bound `settleTurnLane(session)` from the claude stdout consumer (2026-09-13 r3) — the SAME teardown debt as _retireCompaction, for the per-turn LANE decision. An unscoped weekly rejection defers its BUCKET MARK to the end of the turn, and `settleTurnLane` is reachable only from `noteTurnEnd` (claude's `result` record); a turn that ends by the WRAPPER DYING produces none, so the wall was dropped entirely where master's immediate write left a mark — and a dropped wall makes the member read healthy to every other conversation" },

  // streaming / turn state
  _isStreaming:        { owner: 'stdout', persisted: 'wrapper', note: 'explicit protocol-signal streaming flag (never heuristic)' },
  _streamingLabel:     { owner: 'stdout', persisted: null,      note: 'current activity label (thinking/tool/responding)' },
  _autoResume:         { owner: 'ws',     persisted: 'session-config', note: 'per-session auto-continue-after-limit preference (undefined = follow claude.autoResumeOnLimit; 2.368.0)' },
  _outputStyle:        { owner: 'ws',     persisted: 'session-meta',   note: 'the EFFECTIVE response style this session runs with (claude output style / codex Personality). Spawn-scoped on claude (--settings, stream-json has no /output-style); LIVE on codex (thread/settings/update) — capsOf(backend).responseStyle.live decides. 2.368.0, generalized 2.369.58; persisted so a server restart does not report "default" for a session really running one' },
  _streamingKind:      { owner: 'ws',     persisted: null,      note: 'streaming-label kind (compacting) — drives the client Stop two-step guard; set on a /compact send, reset with the label at turn end (2.365.0); also set/cleared by the compact_progress records (§2.11)' },
  _turnState:          { owner: 'stdout', persisted: null,      note: "the harness's OWN turn state, last observed: 'idle'|'running'|'requires_action' (claude system/session_state_changed, env-gated at spawn — §2.5). Drives _isStreaming authoritatively and gives the status bar its third state; in-memory because it is a statement about a RUNNING process (a restart re-derives from the sidecar until the next record)" },
  _turnStateSeen:      { owner: 'stdout', persisted: null,      note: 'THIS session has produced at least one authoritative turn-state record — the latch that stands the derived result/user inference down. False forever on an old CLI / a spawn without the env: degradation is the default path (§3.5)' },
  _inProgressTools:    { owner: 'stdout', persisted: null,      note: "Set<tool_use_id> currently executing, from claude's set_in_progress_tool_use_ids {op:{action,ids}} (caps.inProgressTools). Live-only by nature — the tool cards' spinner set, pushed as 'tools-in-progress' and carried on the attach payload" },
  _codexResetTriedAt:  { owner: 'engine', persisted: null,      note: 'reset-credit attempt stamp (2.368.21) — the one-try floor itself is PER IDENTITY since 2.369.157 r2 (the engine\'s `_resetCreditTries`, read by the verdict\'s `cooldownUntilSec` and the manual preview); this stamp remains the attempt time the result handler falls back to' },
  _resetCreditEvent:   { owner: 'engine', persisted: null,      note: 'the limit EVENT the reset-credit rung last spoke about (`<identity>|<stated reset>`, design-reset-credits §3): the wall card (and the journal line) fire once per event however many records restate the wall; the ask item keys on `_resetCreditAsked` (r2)' },
  _resetCreditOrigin:  { owner: 'engine', persisted: null,      note: 'whose reset-credit attempt the next `reset_credit_result` answers — \'auto\' (the rung) or \'user\' (the manual button, design-reset-credits p2): a failed USER attempt is reported and never walked down the switch/wait ladder; cleared by the result' },
  _resetCreditKey:     { owner: 'engine', persisted: null,      note: 'the credit IDENTITY this session\'s last reset-credit attempt was written for (design-reset-credits r2): the key of the engine\'s per-identity attempt record whose followers the `reset_credit_result` settles, and whose cache the "superseded" check reads' },
  _resetCreditAsked:   { owner: 'engine', persisted: null,      note: 'the limit event (`<identity>|<stated reset>`) the ask-mode For-you decision was filed for — ONE item per event whether it was asked at the wall or, for a cold conversation, after a switch that moved nothing (r2)' },
  _heldPoolMember:     { owner: 'ws',     persisted: 'session-meta heldPoolMember', note: 'the pool member a process on a backend that cannot hot-switch (capsOf(backend).hotSwitch !== verified — codex canonicalizes CODEX_HOME at startup) HOLDS for its whole life, stamped at spawn after resolveForSpawn\'s self-heal; heldPoolMemberFor/sessionBillingMember resolve the session\'s billing member to it so a credit, a reading, a wall and a fire after a pool re-point name the login the process really speaks as (design-reset-credits r2). null = a hot pool / no pool / spawned before the stamp' },
  _heldPoolOrigin:     { owner: 'engine', persisted: 'session-meta heldPoolOrigin', note: 'where `_heldPoolMember` came from (design-reset-credits r3/r4): \'ledger\' = the process was spawned before the stamp existed and the slot-transition ledger named the pool default at its createdAt (accounts.poolMemberOfSession — the last default row before it, else the `from` of the first one after it: STABLE across later moves) — memoized onto the session AND persisted into its meta with the stamp, so a restart restores the answer instead of re-deriving it; \'no-start\' = restored from a meta with no createdAt (boot-restore: the ledger cannot place it ⇒ unknown — r5: the marker itself is PERSISTED into the meta as heldPoolOrigin by the first restore, because the rename / thread-meta writers then persist the boot-filled createdAt); \'unknown\' = only the journal\'s say-once marker (an unknown answer is NOT memoized — one unreadable ledger read must not pin a process unknown for life)' },
  _heldRestartAskedAt: { owner: 'engine', persisted: null,      note: 'when a client was last asked to cold-restart this conversation (`pool-auto-switched`): stamped by the ONE sender (usage-pool-engine sendColdRestart — the default switch, the per-session switch, the auth-failure evict, requestHeldRestart) and by claimColdRestarts (the manual pool target / member-narrowing routes, whose response the client acts on); every one of them leaves out a conversation asked inside 10 min (a second request resumes the conversation twice), and the reset-credit preview names a carrier in that state (`restartPending`)' },
  _resetCreditsSeen:   { owner: 'engine', persisted: null,      note: 'the stored reset-credit count this session\'s own wrapper last reported ({count, at, key} — it rides ONLY the on-demand account/rateLimits/read): the rung\'s fallback when a later passive push dropped it from the account cache, and only for the identity `key` it was read for (p2: a pool session switched to another member never offers the old member\'s count)' },
  _turnWallSigs:       { owner: 'engine', persisted: null,      note: 'wall machine (2.369.0): wall signals accumulated on the CURRENT turn ({at, resetsAtMs, bucket, scopedName, key, slot} — key = the cache key the mark landed on (a REJECTION keys to the credential SLOT since 2026-09-07, a reading keys org-verified), slot = whether that key WAS the validated slot when the rejection arrived); the FIRST keyed signal PINS both for the rest of the turn (rejectionSlotFor — the first record of a rejection re-points the link by itself); the result record classifies' },
  _turnReadingSlot:    { owner: 'engine', persisted: null,      note: 'readings-by-slot (2026-09-07): the validated credential slot ({key, slotOk, at}) this turn\'s quota READINGS are attributed to, resolved ONCE per turn by readingSlotFor and cleared by noteTurnEnd — the twin of _turnWallSigs\' rejection pin. Without it a turn\'s ~20 readings split across the members our own mid-turn re-points moved to, crediting numbers to an account that served none of that turn' },
  _turnLaneDefer:      { owner: 'engine', persisted: null,      note: "the LANE of this turn's UNSCOPED weekly rejections is not decided yet (2026-09-13): [{key, resetsAt, rawType, at}]. claude 2.1.267 has no `seven_day_<model>` type, so a MODEL-cap rejection arrives on the plain `seven_day` lane and only the banner text names the model — writing the event immediately marked the PLAN week 100% spent for three members at once. The bucket mark waits for the banner (kind 'scoped' ⇒ that model's cap, carrying the event's own resetsAt) or, with no banner, for the turn-end evidence rule; the SIGNAL is raised at once so the session is still walled and the pool still moves. Cleared by noteTurnEnd with the other three turn pins" },
  _turnBannerLane:     { owner: 'engine', persisted: null,      note: "the LANE this turn's limit banner named ({kind: a model cap ('scoped' + name) or the plan week, at}; B-ccaa 2026-09-16): laneFromBanner fires when the banner arrives, but a banner that arrived BEFORE the rejection found nothing pending — so a deferral that arrives after it, and the turn-end settle, consult this memo before the evidence rule. A 5-hour banner names no weekly lane and is not kept. Cleared by noteTurnEnd with the other turn pins" },
  _turnWallRefile:     { owner: 'engine', persisted: null,      note: 'the wall attribution PROVED, for this turn, that a rejection record belongs to another member ({from, to, at} — wallRecordTarget re-filed it on the slot ledger plus the window). One wall reaches us through up to three producers and only the rate_limit_event carries a window: the two banner paths state no time at all (parseLimitBanner returns {kind}), so without this they fall back to the turn pin — the member just proved innocent — and one rejection marks two members. Cleared by noteTurnEnd with the other two turn pins' },
  _lastReadingFp:      { owner: 'engine', persisted: null,      note: 'lag shadow (inc-mts8a8mr-ulmm): {key, fp} — the last window fingerprint we filed under a given slot. The SERVER twin of the statusline tool\'s `.slot-<id>` sidecar, and the only evidence left when two members share a weekly reset phase or neither window is established yet ("the link moved but the numbers did not ⇒ leave them where they were")' },
  _readingShadowEndedAt: { owner: 'engine', persisted: null,    note: 'lag shadow: the `at` of the re-point whose shadow has already ended for this session. The FIRST reading that is demonstrably the new credentials\' ends the shadow, and it stays ended — a later in-flight straggler is not evidence that the new credentials have not answered' },
  _turnWorkAfterSig:   { owner: 'engine', persisted: null,      note: 'wall machine: assistant records seen after the last wall signal (work evidence → turn classifies NORMAL)' },
  _wallProbeTimer:     { owner: 'engine', persisted: null,      note: 'wall machine: pending quota-probe backoff timer (30m→1h→2h) when no reset time is known' },
  _arFiring:           { owner: 'auto-resume', persisted: null, note: 'async pre-fire gate in flight (probe+verdict) — tick skips the session meanwhile' },
  _codexLastResetsAt:  { owner: 'engine', persisted: null,      note: 'resets_at (unix sec) of the codex limit that triggered the reset-credit try — auto-resume arms from it if the credit fails (2.368.21)' },
  _codexLastLane:      { owner: 'engine', persisted: null,      note: 'limitId of the codex window that triggered the reset-credit try — the arm carries it so the fresh-window edge cannot be fooled by a sibling lane (2026-09-08)' },
  _codexLimitsWaiters: { owner: 'engine', persisted: null,      note: 'rpc-rate-limits probe waiters (S4 caps-routed quota probe): {resolve,timer} entries settled by the next rate_limits_updated AFTER its cache write; bounded by a timeout' },
  _interruptTimer:     { owner: 'ws',     persisted: null,      note: 'delayed-SIGINT fallback handle (2s, cancel on protocol success)' },
  _wrapperFrameFile:   { owner: 'ws',     persisted: null,      note: 'wrapper understands _frame_file pointers (meta.caps at wrapper boot, chat-wrapper AND codex-chat-wrapper; 2.361.1 skew gate — old wrappers silently DROP pointer lines; positive verdict only)' },
  _userInputAt:        { owner: 'ws',     persisted: null,      note: "the last instant a PERSON sent this session input (ws 'input' keystrokes / 'chat-input'). With _machineInputAt it tells prompt-context whether the turn it is asked about is the owner's own — next-turn group reports ride ONLY those (design-communication-panel §22 D2). In memory: a restart with neither stamp reads as a user turn" },
  _machineInputAt:     { owner: 'deliver', persisted: null,     note: 'the last instant a turn NOBODY TYPED was handed to this session — the delivery ladder at every local rung (conversation-deliver machineTurn) and auto-resume\'s continue (server.js sendToSession). Newer than _userInputAt ⇒ the prompt-context call is a machine turn and the group reports wait (§22 D2)' },
  _msgReachability:    { owner: 'agent',  persisted: 'meta',    note: 'per-session external reach override for agent messaging (2.362.0 Channels v1: inherit|visible|messageable, widening only; set via Session Properties)' },
  _stdinAckReceived:   { owner: 'stdout', persisted: null,      note: 'wrapper _stdin_ack seen — broken-pty detector input' },
  _lastPtyDataAt:      { owner: 'stdout', persisted: null,      note: 'THE liveness stamp: the instant ANY byte last arrived from this session\'s pty bridge (stamped in setupSessionPty, the one place every pty is wired). Read by `ptyQuietSince` for BOTH liveness triggers — the attach probe (no dtach redraw preamble within 4.6s of attach ⇒ the device channel never opened) and ws-handler\'s broken-stdin detector (which used to read session.buffer.length, a strict subset: the terminal branch swallows the preamble and a chat consumer need not append every byte)' },
  _attachProbeHeals:   { owner: 'stdout', persisted: null,      note: 'how many CONSECUTIVE times the attach liveness probe re-attached THIS session locally — bounded at 2 so a systemically silent bridge cannot become a heal loop; reset to 0 by any attach that produces a byte (a lifetime cap would spend a long-lived session\'s heals on unrelated hiccups and leave the next one dark)' },
  _pendingEditor:      { owner: 'ws',     persisted: null,      note: 'Ctrl+G editor open in flight' },

  // goal
  _goal:               { owner: 'goal',   persisted: 'wrapper', note: 'active objective text' },
  _goalStatus:         { owner: 'goal',   persisted: 'wrapper', note: 'active/paused/blocked/usageLimited/…' },
  _goalElapsed:        { owner: 'goal',   persisted: 'wrapper', note: 'seconds used' },
  _goalTokensUsed:     { owner: 'goal',   persisted: 'wrapper', note: 'tokens used' },
  _prevGoal:           { owner: 'goal',   persisted: 'wrapper', note: 'replaced goal for /goal resume' },
  _lastGoalStatusUuid: { owner: 'goal',   persisted: null,      note: 'JSONL goal_status dedup cursor' },
  _goalJsonlFetchAt:   { owner: 'goal',   persisted: null,      note: 'remote transcript pull throttle for goal sync' },

  // model / billing identity
  _servedModel:        { owner: 'stdout', persisted: null,      note: 'last MAIN-THREAD assistant model (never sidechain). WRITTEN through the engine\'s granular consumer `noteServedModel` (like markLimitBanner/recordRateLimitEvent) so the parse and the device feed share ONE implementation of the fallback rule beside it' },
  _servedModelAt:      { owner: 'stdout', persisted: null,      note: 'timestamp of the above' },
  _servedViaFallback:  { owner: 'stdout', persisted: 'meta',      note: "THE CLI ANSWERED WITH A MODEL WE DID NOT ASK FOR (2026-09-13): {from,to,at} from a `fallback` content block / a `system/model_refusal_fallback` record on the MAIN thread. The safety classifier's reroute is announced ONCE and `scope:'session'` — the incident's next 18 assistant records carried claude-opus-4-8 with no marker at all — so the fact has to live on the SESSION, not be re-derived per record. `sessionModelFor` refuses to let a served model that IS this `to` define the session's model; cleared the moment a main-thread record is served by anything else. PERSISTED since 2026-09-13 r3: the round-1 argument (`boot-restore's ladder falls to picked/spawn = the REQUEST model`) is true of the LADDER and false of everything else — a restored conversation got ONE main-thread opus record, nothing on the session refuted it, `servedDefinesModel` said yes and the pool moved it onto a member whose Fable cap was 100 % spent (reproduced on the real engine). The reroute is announced ONCE, so it can never be re-learned from the stream; only the file carries it. Written by the two granular consumers (`noteModelFallback` / `noteServedModel`'s retirement branch), restored at all THREE boot-restore sites. A STALE ONE CANNOT SPEND MONEY — `projectionFamilyFor` answers null (every bucket counts) and the REQUEST model wins — but it is not free either (r3-r2, the round-3 verifier): with every bucket counting it can also refuse a move OFF a member that is hard-dead, because a candidate's cap OUTSIDE this session's family still counts against it (measured on the real engine: a 5h-100% current member kept the conversation while a free member sat beside it, blocked on an Opus cap the session was not using). That is the conservative direction, r2 strands identically — persisting it only makes the state survive a restart instead of being cleared by one — and it self-heals at the first main-thread record served by anything else" },
  _pickedModel:        { owner: 'pool',   persisted: 'meta',    note: 'set-model pick (plan C identity ladder)' },
  _pickedModelAt:      { owner: 'pool',   persisted: 'meta',    note: 'timestamp of the pick' },
  _spawnModel:         { owner: 'ws',     persisted: 'meta',    note: 'model at spawn (identity ladder fallback)' },
  _modelLocked:        { owner: 'pool',   persisted: 'meta',    note: 'per-conversation model lock flag' },
  _lockedModel:        { owner: 'pool',   persisted: 'meta',    note: 'lock target (full id upgraded from the CLI echo)' },
  _fallbackStopFired:  { owner: 'pool',   persisted: null,      note: 'once-per-turn stop-on-fallback belt latch' },
  _apiKeySource:       { owner: 'stdout', persisted: 'meta',    note: "CLI's own init apiKeySource (billing truth)" },
  _effort:             { owner: 'ws',     persisted: 'meta',    note: 'effort the NEXT turn will run at; ws on a client pick, and (2.369.62) the codex stdout consumer from wrapper_meta.effortNext — a `/effort` typed into the chat used to leave this stale for the next resume' },
  _permissionMode:     { owner: 'ws',     persisted: 'meta',    note: 'launch/set permission mode (not in JSONL)' },
  _modelOrigin:        { owner: 'ws',     persisted: 'meta',    note: "WHICH FACT the spawn's model came from (B-6b6d): 'chosen' (a pick for this session) | 'conversation' (its own last turn — codex turn_context / claude's last assistant record) | 'instance' (<prefix>.defaultModel) | 'harness' (nothing sent). Not derivable downstream: the conversation's own value and the instance default are frequently the same string" },
  _effortOrigin:       { owner: 'ws',     persisted: 'meta',    note: "the effort twin of _modelOrigin (B-6b6d). claude has NO conversation source for effort, so a claude resume with no pick is 'harness' — the instance default is a NEW-session default. RE-AUTHORED after the spawn: ws set-effort ⇒ 'chosen'; the codex stdout consumer ⇒ 'conversation' when the wrapper reports a value we never commanded (it adopted the thread's), 'chosen' when it moves away from one we did. EVERY re-author persists it with the value it describes (round 3: the stdout consumer wrote only `effort`, so boot-restore rebuilt the SPAWN's origin for a value the user had changed by hand)" },

  // resume / fork
  _forkRequested:      { owner: 'ws',     persisted: null,      note: 'one-shot fork flag gating id adoption (2.156.1)' },
  _resumeSpawn:        { owner: 'ws',     persisted: 'meta',    note: 'spawn was a --resume (implicit-fork adoption gate)' },
  _sawFirstId:         { owner: 'stdout', persisted: 'meta',    note: 'first id line consumed (adoption bookkeeping)' },
  _resumeSwept:        { owner: 'ws',     persisted: null,      note: 'writer sweep SWEPT: pids for the created reply' },
  _resumeWarning:      { owner: 'ws',     persisted: null,      note: 'non-fatal resume degradation note for the client' },
  _reattachAttempts:   { owner: 'stdout', persisted: null,      note: 'bounded dead-socket re-attach counter' },
  _cwdRecreated:       { owner: 'ws',     persisted: 'meta',    note: 'B-7812 recreate-cwd notice armed' },
  _browserKey:         { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P0 (design-agent-browser-v2 §3.2.1): `bk-<8 hex>`, this CONVERSATION\'s browser identity. Minted once, recovered on resume from data/browser-env/bindings.json FIRST (written at session-stdout\'s one meta choke point and never unlinked by a kill — r5: the conversation→webui-key join is only the second rung, because the kill and pty-exit paths delete the meta file this row persists to, so the join alone never served a Terminate → Resume), re-minted on fork — and a fork\'s record states `forkSourceId` so the choke point never binds the PARENT conversation to the fork\'s key (r6: a claude/codex fork names the parent\'s id until the harness announces its own), while a resume\'s record states `browserKeyFor` = the conversation the key was DECIDED for, so an id the harness announces INSTEAD (an implicit fork adopted by the consumer) is never bound to it and mints its own key on its next resume (r7; the store also refuses to bind a new conversation to a key another one holds). It names the AGENT_BROWSER_SESSION/_NAMESPACE this session spawned with, so two sessions stop opening and closing each other\'s tabs; persisted because keying on the webui id (which changes every resume) leaks a browser, a daemon and a pinned tab per resume' },
  _browserVariant:     { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P0 (§3.2.2/D12): which user-data-dir rung this spawn landed on — D (generated config, truly ephemeral, carries the effective fence) / C (per-session scratch dir under data/, swept) / N (the three names alone, reachable ONLY when the effective config names no profile — then each daemon gets the CLI\'s own ephemeral dir; also where every FENCED session lands when D is unavailable, because rung C is an AGENT_BROWSER_PROFILE the CLI refuses beside --allowed-domains — r4) / none (nothing emitted, today\'s shared browser: the local floor when the config names a profile and neither D nor C is available — the names alone would put N browsers on ONE dir and the second fails to launch, measured) / H (REMOTE: decided on the host at spawn between C and N by that machine\'s own config, through the `browser` fragment of buildRemoteExec). The design\'s A and B are named rejects (browser-profiles.REJECTED_VARIANTS, both measured to collide). Recorded so a log line or a properties row states the rung instead of re-deriving it' },
  _browserProfileId:   { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P1 (design-agent-browser-v2 §3.2.5): the profile this session is PINNED to (`bp-<8 hex>`), or null = ephemeral. Decided at spawn by the keeper\'s ladder (explicit > this conversation\'s pin > Task-Group default > instance default > none) and rewritten by the pin route mid-session; the conversation-level fact lives in data/browser-profiles.json `pins` (keyed by browserKey), this is the session\'s copy for the properties row and the restart.' },
  _browserPinOrigin:   { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P1: WHICH rung chose `_browserProfileId` — one of browser-profiles.PIN_ORIGINS (chosen / conversation / task-group / instance / harness), stated by the ladder, never inferred (the B-6b6d rule).' },
  _browserEnv:         { owner: 'ws',     persisted: 'meta',    note: 'agent-browser P2 (design §4.2): the P0 spawn pairs (`AGENT_BROWSER_*=…`) this process browses with, kept so the live view of an EPHEMERAL browser (no attachment) asks `stream status` under exactly these — never a re-run of the ladder, which would rebuild the generated config (the r3 finding). null = nothing emitted (rung none / integration off / remote).' },
  _browserProfileActive: { owner: 'ws',   persisted: 'meta',    note: 'agent-browser P2 (design §3.8 layer ③): the profile the agent LAST ACTUALLY USED — stamped by /api/agent/browser/resolve on every successful CLI command (an attachment\'s id, or \'\' for the ephemeral browser); null = the agent has not issued a browser command yet. Beside `_browserProfileId` (the PINNED default) it is the status-bar Browser chip\'s pair: amber when they differ. Published as `browserProfileActive` in active-sessions and gated by its own LIVE_SESSION_FACTS digest.' },
  _worktree:           { owner: 'ws',     persisted: 'meta',    note: 'the user asked THIS session to run in its own git worktree (claude --worktree, owner ruling 9). Persisted so a restart/resume keeps describing the session honestly and the badge survives; the FLAG itself is only re-emitted on a fork (worktreeSpawnArgs) because the CLI re-enters its recorded worktree on --resume by itself' },
  _worktreePath:       { owner: 'stdout', persisted: 'meta',    note: 'the worktree directory the CLI ITSELF announced in its init frame `cwd` (typed record, never inferred: the CLI chdir\'s into <repo>/.claude/worktrees/<name> and reports it). null until the first init frame; Session Properties shows it'  },

  // remote / transport
  _remoteState:        { owner: 'stdout', persisted: 'wrapper', note: 'remote keeper link state (reconnecting chip)' },
  _vcs:                { owner: 'brain',  persisted: 'meta',    note: "design-unknown-records (2026-09-21): the LAST claude `vcs_state_changed` fact {kind, branch, cwd, at} — session-brain noteVcsState writes it from either feed; rides active-sessions as `vcs` (the card's git chip) + the `session-vcs` push (explorer refresh); persisted so the chip survives a restart" },
  _prLinks:            { owner: 'brain',  persisted: 'meta',    note: "design-unknown-records (2026-09-21): the published changes this session announced (`code_change_published` → [{url, identifier, repo, action, provider, at}], ≤20, keyed by url) — session-brain notePublishedChange; rides active-sessions as `prLinks` (the card's PR chips); the url is UNVERIFIED by the CLI's own words — shown, never fetched" },
  _remotePort:         { owner: 'ws',     persisted: null,      note: 'reverse-tunnel port for VIBESPACE_API' },
  _agentdSession:      { owner: 'ws',     persisted: 'meta',    note: 'daemon pipe-session marker (R6/M2)' },
  _agentdCfgFile:      { owner: 'ws',     persisted: null,      note: 'attach-cli cfg file path (cleanup)' },
  _dialDeviceId:       { owner: 'dial',   persisted: 'meta',    note: 'owning dial device id' },
  _dialReversePort:    { owner: 'dial',   persisted: null,      note: 'device-side reverse forward port' },
  _bridgePort:         { owner: 'dial',   persisted: 'meta',    note: 'DialSessionBridge loopback port' },

  // agent-facing bookkeeping (src/agent-routes.js) — the injection ladder's
  // per-session "already delivered this" marks, plus the Stop nudge's clock.
  // Registered 2026-09-08: the detector only saw `session.`/`sess.` receivers,
  // and every one of these is written through a local named `s`/`sessionObj`.
  _lastStopNudge:      { owner: 'agent-routes', persisted: 'spend-budget', note: "the Stop bookkeeping nudge's cooldown (design-account-hardening D8). The in-memory mirror of the PERSISTED record in data/spend-budget.json (src/server/spend-guard.js `nudgeRec`/`noteNudge`): it was in-memory ONLY, so every release restart handed the largest measured automatic spender (603 mini-turns over two months here, 21 of them on one conversation inside one hour) a fresh cooldown. The route takes the NEWER of the two" },
  _preambleSeen:       { owner: 'agent-routes', persisted: null, note: 'hash of the task-context preamble already delivered to this session (re-delivery only when the content changes)' },
  _toolsIntroSeen:     { owner: 'agent-routes', persisted: null, note: 'the baseline tools intro has been delivered to this no-task session (SessionStart)' },
  _mgrIntroSeen:       { owner: 'agent-routes', persisted: null, note: 'the manager-agent intro has been delivered (shared latch between SessionStart and prompt-context — whichever delivers first wins)' },
  _groupSeenAt:        { owner: 'agent-routes', persisted: null, note: '{groupId: contentUpdatedAt} the session has already been shown — the per-turn group-diff cursor' },
  _ctxSig:             { owner: 'agent-routes', persisted: null, note: '{groupId: contextDirSignature} at last delivery — a ctx folder change re-injects' },
  _groupSnap:          { owner: 'agent-routes', persisted: null, note: '{groupId: snapshotForDiff} at last delivery — what the update diff is computed against' },

  // misc consumers
  _sizeOwnerWs:        { owner: 'ws',     persisted: null,      note: 'size-override owner connection' },
  _childPid:           { owner: 'boot',   persisted: 'meta',    note: 'the pid INSIDE the dtach session (the wrapper/CLI, not our pty) — restored from session-meta at boot and used by the kill path' },
  _restoreAgentTasks:  { owner: 'boot',   persisted: null,      note: "the wrapper meta's subagent task map, carried from restore until setupSessionPty's watcher is armed, then cleared (null = consumed)" },
  _todos:              { owner: 'stdout', persisted: null,      note: 'TodoWrite/TaskCreate-derived {done,total,current}' },
  _sbSeen:             { owner: 'brain',  persisted: null,      note: 'first-writer-wins record gate (bounded set)' },
  _codexThreadBaseline: { owner: 'ws',    persisted: null,      note: 'codex thread listing baseline for capture' },
  _captureReservedThreadId: { owner: 'ws', persisted: null,     note: 'codex reserved thread id during create' },
};

module.exports = { SESSION_FIELDS };
